### ISSUE TITLE
Issues with Oculus' UE5 v39 Branch

### ISSUE THREAD

**Issue by theorystudios** [oculus-samples/Unreal-SharedSpaces#10]
Just got to opening the latest Oculus branch, V39 release 1.71. Got a good amount of errors:

`
[25/141] Compile Module.OculusPlatform.cpp
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\NetConnectionForOculus.cpp(85): warning C4996: 'UNetConnection::State': EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\NetConnectionForOculus.cpp(148): warning C4996: 'UNetConnection::State': EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\NetDriverForOculus.cpp(264): warning C4996: 'UNetConnection::State': EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\NetDriverForOculus.cpp(397): warning C4996: 'UNetConnection::State': EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\NetDriverForOculus.cpp(407): warning C4996: 'UNetConnection::State': EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\NetDriverForOculus.cpp(420): warning C4996: 'UNetConnection::State': EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\NetDriverForOculus.cpp(429): warning C4996: 'UNetConnection::State': EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\NetDriverForOculus.cpp(439): warning C4996: 'UNetConnection::State': EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\NetDriverForOculus.cpp(447): warning C4996: 'UNetConnection::State': EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\NetDriverForOculus.cpp(509): warning C4996: 'UNetConnection::State': EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(41): error C2065: 'ovrMessage_Notification_GroupPresence_JoinIntentReceived': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(45): error C2065: 'ovrMessage_Notification_GroupPresence_LeaveIntentReceived': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(49): error C2065: 'ovrMessage_Notification_GroupPresence_InvitationsSent': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(124): error C3861: 'ovr_LaunchDetails_GetDestinationApiName': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(126): error C3861: 'ovr_LaunchDetails_GetLobbySessionID': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(127): error C3861: 'ovr_LaunchDetails_GetMatchSessionID': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(129): error C3861: 'ovr_LaunchDetails_GetTrackingID': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(909): error C3861: 'ovr_User_GetDisplayName': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(919): error C3861: 'ovr_User_GetPresenceDestinationApiName': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(922): error C3861: 'ovr_User_GetPresenceLobbySessionId': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(925): error C3861: 'ovr_User_GetPresenceMatchSessionId': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(971): error C3861: 'ovr_RichPresence_GetDestinations': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(983): error C2065: 'ovrDestinationArrayHandle': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(983): error C2146: syntax error: missing ';' before identifier 'DestinationArrayHandle'
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(983): error C2065: 'DestinationArrayHandle': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(983): error C3861: 'ovr_Message_GetDestinationArray': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(985): error C2065: 'DestinationArrayHandle': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(985): error C3861: 'ovr_DestinationArray_GetSize': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(987): error C2065: 'ovrDestinationHandle': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(987): error C2146: syntax error: missing ';' before identifier 'DestinationHandle'
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(987): error C2065: 'DestinationHandle': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(987): error C2065: 'DestinationArrayHandle': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(987): error C3861: 'ovr_DestinationArray_GetElement': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(990): error C2065: 'DestinationHandle': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(990): error C3861: 'ovr_Destination_GetApiName': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(991): error C2065: 'DestinationHandle': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(991): error C3861: 'ovr_Destination_GetDeeplinkMessage': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(992): error C2065: 'DestinationHandle': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(992): error C3861: 'ovr_Destination_GetDisplayName': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1011): error C3861: 'ovr_RichPresence_GetDestinations': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1027): error C2065: 'ovrDestinationArrayHandle': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1027): error C2146: syntax error: missing ';' before identifier 'DestinationArrayHandle'
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1027): error C2065: 'DestinationArrayHandle': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1027): error C3861: 'ovr_Message_GetDestinationArray': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1028): error C2065: 'DestinationArrayHandle': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1028): error C3861: 'ovr_DestinationArray_GetSize': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1030): error C2065: 'ovrDestinationHandle': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1030): error C2146: syntax error: missing ';' before identifier 'DestinationHandle'
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1030): error C2065: 'DestinationHandle': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1030): error C2065: 'DestinationArrayHandle': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1030): error C3861: 'ovr_DestinationArray_GetElement': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1032): error C2065: 'DestinationHandle': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1032): error C3861: 'ovr_Destination_GetApiName': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1038): error C2065: 'DestinationHandle': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1038): error C3861: 'ovr_Destination_GetDeeplinkMessage': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1039): error C2065: 'DestinationHandle': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1039): error C3861: 'ovr_Destination_GetDisplayName': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1074): error C3861: 'ovr_RichPresenceOptions_SetLobbySessionId': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1075): error C3861: 'ovr_RichPresenceOptions_SetMatchSessionId': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1118): error C3861: 'ovr_GroupPresence_Clear': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1156): error C2065: 'ovrGroupPresenceOptionsHandle': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1156): error C2146: syntax error: missing ';' before identifier 'GroupPresenceOptions'
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1156): error C2065: 'GroupPresenceOptions': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1156): error C3861: 'ovr_GroupPresenceOptions_Create': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1157): error C2065: 'GroupPresenceOptions': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1157): error C3861: 'ovr_GroupPresenceOptions_SetDestinationApiName': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1158): error C2065: 'GroupPresenceOptions': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1158): error C3861: 'ovr_GroupPresenceOptions_SetLobbySessionId': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1159): error C2065: 'GroupPresenceOptions': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1159): error C3861: 'ovr_GroupPresenceOptions_SetMatchSessionId': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1160): error C2065: 'GroupPresenceOptions': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1160): error C3861: 'ovr_GroupPresenceOptions_SetIsJoinable': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1162): error C2065: 'GroupPresenceOptions': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1162): error C3861: 'ovr_GroupPresence_Set': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1185): error C2065: 'GroupPresenceOptions': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1185): error C3861: 'ovr_GroupPresenceOptions_Destroy': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1194): error C3861: 'ovr_GroupPresence_SetDestination': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1221): error C3861: 'ovr_GroupPresence_SetIsJoinable': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1248): error C3861: 'ovr_GroupPresence_SetLobbySession': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1276): error C3861: 'ovr_GroupPresence_SetLobbySession': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1318): error C2065: 'ovrInviteOptionsHandle': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1318): error C2146: syntax error: missing ';' before identifier 'InviteOptions'
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1318): error C2065: 'InviteOptions': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1318): error C3861: 'ovr_InviteOptions_Create': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1322): error C2065: 'InviteOptions': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1322): error C3861: 'ovr_InviteOptions_AddSuggestedUser': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1327): error C2065: 'InviteOptions': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1327): error C3861: 'ovr_GroupPresence_LaunchInvitePanel': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1340): error C2065: 'ovrInvitePanelResultInfoHandle': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1340): error C2146: syntax error: missing ';' before identifier 'InvitePanelResultInfoHandle'
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1340): error C2065: 'InvitePanelResultInfoHandle': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1340): error C3861: 'ovr_Message_GetInvitePanelResultInfo': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1341): error C2065: 'InvitePanelResultInfoHandle': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1341): error C3861: 'ovr_InvitePanelResultInfo_GetInvitesSent': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1349): error C2065: 'InviteOptions': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1349): error C3861: 'ovr_InviteOptions_Destroy': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1358): error C2065: 'ovrRosterOptionsHandle': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1358): error C2146: syntax error: missing ';' before identifier 'RosterOptions'
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1358): error C2065: 'RosterOptions': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1358): error C3861: 'ovr_RosterOptions_Create': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1362): error C2065: 'RosterOptions': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1362): error C3861: 'ovr_RosterOptions_AddSuggestedUser': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1367): error C2065: 'RosterOptions': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1367): error C3861: 'ovr_GroupPresence_LaunchRosterPanel': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1384): error C2065: 'RosterOptions': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1384): error C3861: 'ovr_RosterOptions_Destroy': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1399): error C2065: 'ovrGroupPresenceJoinIntentHandle': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1399): error C2146: syntax error: missing ';' before identifier 'JoinIntentHandle'
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1399): error C2065: 'JoinIntentHandle': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1399): error C3861: 'ovr_Message_GetGroupPresenceJoinIntent': identifier not found
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1401): error C2065: 'JoinIntentHandle': undeclared identifier
F:\git\lathos-unreal\Plugins\OculusPlatform\Source\OculusPlatform\Private\OculusPlatformSubsystem.cpp(1401): fatal error C1003: error count exceeds 100; stopping compilation`

[99/141] Compile Module.PhotonNetDriver.cpp
F:\git\lathos-unreal\Plugins\PhotonNetDriver\Source\PhotonNetDriver\Private\PhotonIpNetDriver.cpp(258): warning C4996: 'UNetConnection::State': EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
F:\git\lathos-unreal\Plugins\PhotonNetDriver\Source\PhotonNetDriver\Private\PhotonIpNetDriver.cpp(384): warning C4996: 'UNetConnection::State': EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
F:\git\lathos-unreal\Plugins\PhotonNetDriver\Source\PhotonNetDriver\Private\PhotonIpNetDriver.cpp(394): warning C4996: 'UNetConnection::State': EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
F:\git\lathos-unreal\Plugins\PhotonNetDriver\Source\PhotonNetDriver\Private\PhotonIpNetDriver.cpp(407): warning C4996: 'UNetConnection::State': EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
F:\git\lathos-unreal\Plugins\PhotonNetDriver\Source\PhotonNetDriver\Private\PhotonIpNetDriver.cpp(416): warning C4996: 'UNetConnection::State': EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
F:\git\lathos-unreal\Plugins\PhotonNetDriver\Source\PhotonNetDriver\Private\PhotonIpNetDriver.cpp(426): warning C4996: 'UNetConnection::State': EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
F:\git\lathos-unreal\Plugins\PhotonNetDriver\Source\PhotonNetDriver\Private\PhotonIpNetDriver.cpp(434): warning C4996: 'UNetConnection::State': EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
F:\git\lathos-unreal\Plugins\PhotonNetDriver\Source\PhotonNetDriver\Private\PhotonIpNetDriver.cpp(489): warning C4996: 'UNetConnection::State': EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
F:\git\lathos-unreal\Plugins\PhotonNetDriver\Source\PhotonNetDriver\Private\PhotonNetConnection.cpp(87): warning C4996: 'UNetConnection::State': EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
F:\git\lathos-unreal\Plugins\PhotonNetDriver\Source\PhotonNetDriver\Private\PhotonNetConnection.cpp(150): warning C4996: 'UNetConnection::State': EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.

**Comment by els-oculus** [comment]
SharedSpaces currently requires the Oculus fork of the UE4.27 game engine, as mentioned in the build instructions (see [README.md](https://github.com/oculus-samples/Unreal-SharedSpaces/blob/main/README.md)).

UE5 support is being worked on, however!

**Comment by theorystudios** [comment]
That's awesome @els-oculus  - how soon do you think UE5 support will be available?

**Comment by els-oculus** [comment]
One of the key changes is that you have to explicitly turn on the Oculus VR plugin.
After that, UE5 has a few modified APIs that you can easily fix.

This said, UE4.27 is very stable, and I would stick with it for the coming months.
There is an update for SharedSpaces for Unreal that is coming to you soon, and it is also targeting 4.27.

**Comment by theorystudios** [comment]
Thanks so much @els-oculus , appreciate the reply! We're great on 4.27, staying there for the foreseeable future until we're feature parity on the UE5 branch.

One thought: is there a world where more features could be exposed here? For example, In App Purchases in the Oculus SDK aren't exposed by the current Oculus plugin.

We have a problem where we rely on a third party plugin to expose those features, SharedSpace's Oculus subsystem for Inviting Friends, and of course the standard Oculus build for things like AppSW. It would be great to have a future where we didn't have three different touch points.

Yes we could always expose all of this ourselves, but time, effort and budget reduce that bandwidth of what we can focus on 😅

**Comment by els-oculus** [comment]
First, a note regarding UE5: https://developer.oculus.com/downloads/package/unreal-engine-5-integration/#known-issues

Second: yes, we are going to expose all OVR Platform APIs through a non-OSS plugin.  That's the update that I was covertly referring to in my previous comment.  We actually have just tested the updated SharedSpaces today.  This should reach this branch in the coming days, so stay tuned!

**Comment by theorystudios** [comment]
That’s awesome @els-oculus ! Thanks again for all the updates and I look forward to these updates. Feel free to close the issue too :)

**Comment by els-oculus** [comment]
Hello @theorystudios,

We updated SharedSpaces to the new plugin discussed above.
Please let us know what you think at [devtech-showcases@fb.com](mailto:devtech-showcases@fb.com)!

**Comment by theorystudios** [comment]
I can confirm all of this loads initially and seems to work - now to port & integrate. Thank you a billion @els-oculus !

![UE4Editor_zzcqNKNJla](https://user-images.githubusercontent.com/14636906/169192641-3d80d1bf-0f1c-48a2-857c-e51eaef0248a.jpg)
