### ISSUE TITLE
Not able to run build on windows laptop is it because of space ? 

### ISSUE THREAD

**Issue by ssshammi** [oculus-samples/Unreal-SharedSpaces#13]
I was able to generate the project files using .\GenerateProjectFiles.bat -Game SharedSpaces -Engine <full path to Unreal-SharedSpaces directory>\SharedSpaces.uproject

But able to build the project in visual studio and I got the below log. 

> 1>------ Build started: Project: DotNETUtilities, Configuration: Debug Any CPU ------
> 1>  DotNETUtilities -> C:\Learning Projects\Games\UnrealEngine\Engine\Binaries\DotNET\DotNETUtilities.dll
> 2>------ Build started: Project: UnrealBuildTool, Configuration: Debug Any CPU ------
> 2>  UnrealBuildTool -> C:\Learning Projects\Games\UnrealEngine\Engine\Binaries\DotNET\UnrealBuildTool.exe
> 3>------ Build started: Project: SharedSpaces, Configuration: Debug Win32 ------
> 3>Using 'git status' to determine working set for adaptive non-unity build (C:\Learning Projects\Games\UnrealEngine).
> 3>Using 'git status' to determine working set for adaptive non-unity build (C:\Learning Projects\Games\Unreal-SharedSpaces).
> 3>Creating makefile for SharedSpaces (.uproject file is newer)
> 3>Building SharedSpaces...
> 3>Using Visual Studio 2019 14.29.30138 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133) and Windows 10.0.16299.0 SDK (C:\Program Files (x86)\Windows Kits\10).
> 3>Building 3 actions with 12 processes...
> 3>  [1/3] Module.OVRPlatform.cpp
> 3>C:\Learning Projects\Games\Unreal-SharedSpaces\Plugins\OVRPlatform\Source\OVRPlatform\Private\OVRPlatformRequestsConverters.h(70): error C4018: '<': signed/unsigned mismatch
> 3>C:\Learning Projects\Games\Unreal-SharedSpaces\Plugins\OVRPlatform\Source\OVRPlatform\Private\OVRPlatformRequestsConverters.h(82): error C4018: '<': signed/unsigned mismatch
> 3>C:\Learning Projects\Games\Unreal-SharedSpaces\Plugins\OVRPlatform\Source\OVRPlatform\Private\OVRPlatformRequestsConverters.h(372): error C4018: '<': signed/unsigned mismatch
> 3>C:\Learning Projects\Games\Unreal-SharedSpaces\Plugins\OVRPlatform\Source\OVRPlatform\Private\OVRPlatformRequestsConverters.h(408): error C4018: '<': signed/unsigned mismatch
> 3>C:\Learning Projects\Games\Unreal-SharedSpaces\Plugins\OVRPlatform\Source\OVRPlatform\Private\OVRPlatformRequestsConverters.h(444): error C4018: '<': signed/unsigned mismatch
> 3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets(45,5): error MSB3073: The command ""C:\Learning Projects\Games\UnrealEngine\Engine\Build\BatchFiles\Build.bat" SharedSpaces Win32 Debug -Project="C:\Learning Projects\Games\Unreal-SharedSpaces\SharedSpaces.uproject" -WaitMutex -FromMsBuild" exited with code 6.
> 3>Done building project "SharedSpaces.vcxproj" -- FAILED.
> ========== Build: 2 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by els-oculus** [comment]
You must be building a 32 bit editor.   Switch to 64 bits and report back, please.

**Comment by els-oculus** [comment]
Quest apps need to be 64 bits: https://developer.oculus.com/blog/quest-submission-policy-update-64-bit-by-default/
Nonetheless your comment made me look at the converter code and I went ahead and cleaned it up for 32 bit.  :)
Thanks for pointing that out, ssshammi!

**Comment by ssshammi** [comment]
@els-oculus Thanks, I think it might have also been the .net version 4.6.1 so this time I was able to run the build with 64 bit selected by default. Thanks
