### ISSUE TITLE
Updating to OVR Plugin update.

### ISSUE THREAD

**Issue by owlandfox** [oculus-samples/Unreal-SharedSpaces#14]
After updating my project with the latest update to the OVR plugin I can no longer play the project in editor. I have uploaded to the applab and project plays fine there. The only error in log states - 

LogSharedSpaces: Display: Request generator failure.
LogSharedSpaces: Display: FATAL ERROR: Login failure.
LogSharedSpaces: Display: Request generator failure.

What could be the issue?

**Comment by els-oculus** [comment]
First things to check:
- DefaultEngine.ini: your app ids are still there (both MobileAppId and RiftAppId)
- Photon app id in PhotonLBClient.h (really this should be updated to be in DefaultEngine.ini, too)

**Comment by owlandfox** [comment]
Thanks that worked!
