### ISSUE TITLE
do i need to add oculus quest id when running in standalone mode?

### ISSUE THREAD

**Issue by ssshammi** [oculus-samples/Unreal-SharedSpaces#16]
Hi I was able to run the build with photon 
i have two questions do i need to change 
const FString serverAddress = TEXT("ns.exitgames.com");
in case i am using photon cloud server do i need to change ns.exitgames.com if yes what is the URL, i am not hosting the server on local.

Second question is when i run the sharespaces example in without connecting to device i get LogSharedSpaces: Display: FATAL ERROR: Login failure.  and it will auto close the app. 
do i need to add values for .
MobileAppId=<quest-app-id-here>  
RiftAppId=<rift-app-id-here> // what should i add here i do not have a rift.

Can you please update the document if these values need to be changed?

`LogTemp: Repeating last play command: Selected Viewport
LogPlayLevel: PlayLevel: No blueprints needed recompiling
PIE: New page: PIE session: Lobby (26-May-2022, 2:45:59 am)
LogPlayLevel: Creating play world package: /Game/SharedSpaces/Maps/UEDPIE_0_Lobby
LogPlayLevel: PIE: StaticDuplicateObject took: (0.004471s)
LogAIModule: Creating AISystem for world Lobby
LogPlayLevel: PIE: World Init took: (0.001319s)
LogPlayLevel: PIE: Created PIE world by copying editor world from /Game/SharedSpaces/Maps/Lobby.Lobby to /Game/SharedSpaces/Maps/UEDPIE_0_Lobby.Lobby (0.006247s)
LogUObjectHash: Compacting FUObjectHashTables data took   1.79ms
LogOvrPlatform: Display: UOvrPlatformSubsystem::Initialize
LogOvrPlatform: Display: Login with current credentials
LogOvrPlatform: Display: UOvrPlatformSubsystem::InitWithWindowsPlatform: ovr_PlatformInitializeWindows successful
LogSharedSpaces: Display: Oculus platform successfully initialized.
LogSharedSpaces: Display: Use ASDW to move, mouse for camera orientation, C to change color and SPACE to jump.
LogAudio: Display: Creating Audio Device:                 Id: 8, Scope: Unique, Realtime: True
LogAudioMixer: Display: Audio Mixer Platform Settings:
LogAudioMixer: Display:     Sample Rate:                          48000
LogAudioMixer: Display:     Callback Buffer Frame Size Requested: 1024
LogAudioMixer: Display:     Callback Buffer Frame Size To Use:    1024
LogAudioMixer: Display:     Number of buffers to queue:           2
LogAudioMixer: Display:     Max Channels (voices):                32
LogAudioMixer: Display:     Number of Async Source Workers:       0
LogAudio: Display: AudioDevice MaxSources: 32
LogAudio: Display: Audio Spatialization Plugin: None (built-in).
LogAudio: Display: Audio Reverb Plugin: None (built-in).
LogAudio: Display: Audio Occlusion Plugin: None (built-in).
LogAudioMixer: Display: Initializing audio mixer.
LogAudioMixer: Display: 0: FrontLeft
LogAudioMixer: Display: 1: FrontRight
LogAudioMixer: Display: Using Audio Device Speaker (Realtek(R) Audio)
LogAudioMixer: Display: Initializing Sound Submixes...
LogAudioMixer: Display: Creating Master Submix 'MasterSubmixDefault'
LogAudioMixer: Display: Creating Master Submix 'MasterReverbSubmixDefault'
LogAudioMixer: Display: Creating Master Submix 'MasterEQSubmixDefault'
LogAudioMixer: FMixerPlatformXAudio2::StartAudioStream() called
LogAudioMixer: Display: Output buffers initialized: Frames=1024, Channels=2, Samples=2048
LogAudioMixer: Display: Starting AudioMixerPlatformInterface::RunInternal()
LogAudioMixer: Display: FMixerPlatformXAudio2::SubmitBuffer() called for the first time
LogInit: FAudioDevice initialized.
LogAudio: Display: Audio Device (ID: 8) registered with world 'Lobby'.
LogLoad: Game class is 'SharedSpacesGameMode_C'
LogWorld: Bringing World /Game/SharedSpaces/Maps/UEDPIE_0_Lobby.Lobby up for play (max tick rate 0) at 2022.05.26-01.46.04
LogWorld: Bringing up level for play took: 0.001483
LogOnline: OSS: Creating online subsystem instance for: :Context_11
LogOnline: Verbose: OSS: Created thread (ID:30660).
LogSharedSpaces: Display: First player start without a tag.
LogOnlineVoice: OSS: Voice interface disabled by config [OnlineSubsystem].bHasVoiceEnabled
LogSharedSpaces: Display: Local character current destination:  
PIE: Server logged in
PIE: Play in editor total start time 4.725 seconds.
LogOvrPlatform: Warning: DeltaTime was 4.751278 seconds.  Time sensitive oculus notifications may time out.
LogSharedSpaces: Display: Must call get_signature first (1971051)
LogSharedSpaces: Display: FATAL ERROR: Login failure.
LogSharedSpaces: Display: Missing entitlement for <rift-app-id-here> (1971031)
LogSlate: Updating window title bar state: overlay mode, drag disabled, window buttons hidden, title bar hidden
LogWorld: BeginTearingDown for /Game/SharedSpaces/Maps/UEDPIE_0_Lobby
LogSharedSpaces: Display: Shutdown
LogOvrPlatform: Display: UOvrPlatformSubsystem::Deinitialize
LogWorld: UWorld::CleanupWorld for Lobby, bSessionEnded=true, bCleanupResources=true
LogSlate: InvalidateAllWidgets triggered.  All widgets were invalidated
LogOnline: VeryVerbose: OSS: FOnlineSubsystemNull::Shutdown()
LogOnline: VeryVerbose: OSS: FOnlineAsyncTaskManager::Stop() ActiveTask:0000000000000000 Tasks[0/0]
LogOnline: VeryVerbose: OSS: FOnlineAsyncTaskManager::Exit() started
LogOnline: VeryVerbose: OSS: FOnlineAsyncTaskManager::Exit() finished
LogPlayLevel: Display: Shutting down PIE online subsystems
LogSlate: InvalidateAllWidgets triggered.  All widgets were invalidated
LogAudio: Display: Audio Device unregistered from world 'None'.
LogAudioMixer: FMixerPlatformXAudio2::StopAudioStream() called
LogAudioMixer: FMixerPlatformXAudio2::StopAudioStream() called
LogSlate: Updating window title bar state: overlay mode, drag disabled, window buttons hidden, title bar hidden
LogUObjectHash: Compacting FUObjectHashTables data took   1.83ms
LogPlayLevel: Display: Destroying online subsystem :Context_11
LogOnline: VeryVerbose: OSS: FOnlineSubsystemNull::Shutdown()
LogUObjectHash: Compacting FUObjectHashTables data took   1.81ms
LogPlayLevel: PlayLevel: No blueprints needed recompiling
PIE: New page: PIE session: Lobby (26-May-2022, 2:48:05 am)
LogPlayLevel: Creating play world package: /Game/SharedSpaces/Maps/UEDPIE_0_Lobby
LogPlayLevel: PIE: StaticDuplicateObject took: (0.004362s)
LogAIModule: Creating AISystem for world Lobby
LogPlayLevel: PIE: World Init took: (0.000952s)
LogPlayLevel: PIE: Created PIE world by copying editor world from /Game/SharedSpaces/Maps/Lobby.Lobby to /Game/SharedSpaces/Maps/UEDPIE_0_Lobby.Lobby (0.005596s)
LogUObjectHash: Compacting FUObjectHashTables data took   1.64ms
LogOvrPlatform: Display: UOvrPlatformSubsystem::Initialize
LogOvrPlatform: Display: Login with current credentials
LogOvrPlatform: Display: UOvrPlatformSubsystem::InitWithWindowsPlatform: ovr_PlatformInitializeWindows successful
LogSharedSpaces: Display: Oculus platform successfully initialized.
LogSharedSpaces: Display: Use ASDW to move, mouse for camera orientation, C to change color and SPACE to jump.
LogAudio: Display: Creating Audio Device:                 Id: 9, Scope: Unique, Realtime: True
LogAudioMixer: Display: Audio Mixer Platform Settings:
LogAudioMixer: Display:     Sample Rate:                          48000
LogAudioMixer: Display:     Callback Buffer Frame Size Requested: 1024
LogAudioMixer: Display:     Callback Buffer Frame Size To Use:    1024
LogAudioMixer: Display:     Number of buffers to queue:           2
LogAudioMixer: Display:     Max Channels (voices):                32
LogAudioMixer: Display:     Number of Async Source Workers:       0
LogAudio: Display: AudioDevice MaxSources: 32
LogAudio: Display: Audio Spatialization Plugin: None (built-in).
LogAudio: Display: Audio Reverb Plugin: None (built-in).
LogAudio: Display: Audio Occlusion Plugin: None (built-in).
LogAudioMixer: Display: Initializing audio mixer.
LogAudioMixer: Display: 0: FrontLeft
LogAudioMixer: Display: 1: FrontRight
LogAudioMixer: Display: Using Audio Device Speaker (Realtek(R) Audio)
LogAudioMixer: Display: Initializing Sound Submixes...
LogAudioMixer: Display: Creating Master Submix 'MasterSubmixDefault'
LogAudioMixer: Display: Creating Master Submix 'MasterReverbSubmixDefault'
LogAudioMixer: Display: Creating Master Submix 'MasterEQSubmixDefault'
LogAudioMixer: FMixerPlatformXAudio2::StartAudioStream() called
LogAudioMixer: Display: Output buffers initialized: Frames=1024, Channels=2, Samples=2048
LogAudioMixer: Display: Starting AudioMixerPlatformInterface::RunInternal()
LogAudioMixer: Display: FMixerPlatformXAudio2::SubmitBuffer() called for the first time
LogInit: FAudioDevice initialized.
LogAudio: Display: Audio Device (ID: 9) registered with world 'Lobby'.
LogLoad: Game class is 'SharedSpacesGameMode_C'
LogWorld: Bringing World /Game/SharedSpaces/Maps/UEDPIE_0_Lobby.Lobby up for play (max tick rate 3) at 2022.05.26-01.48.09
LogWorld: Bringing up level for play took: 0.001359
LogOnline: OSS: Creating online subsystem instance for: :Context_12
LogOnline: Verbose: OSS: Created thread (ID:29364).
LogSharedSpaces: Display: First player start without a tag.
LogOnlineVoice: OSS: Voice interface disabled by config [OnlineSubsystem].bHasVoiceEnabled
LogSharedSpaces: Display: Local character current destination:  
PIE: Server logged in
PIE: Play in editor total start time 4.699 seconds.
LogOvrPlatform: Warning: DeltaTime was 4.723348 seconds.  Time sensitive oculus notifications may time out.
LogSharedSpaces: Display: Must call get_signature first (1971051)
LogSharedSpaces: Display: FATAL ERROR: Login failure.
LogSharedSpaces: Display: Missing entitlement for <rift-app-id-here> (1971031)
LogSlate: Updating window title bar state: overlay mode, drag disabled, window buttons hidden, title bar hidden
LogWorld: BeginTearingDown for /Game/SharedSpaces/Maps/UEDPIE_0_Lobby
LogSharedSpaces: Display: Shutdown
LogOvrPlatform: Display: UOvrPlatformSubsystem::Deinitialize
LogWorld: UWorld::CleanupWorld for Lobby, bSessionEnded=true, bCleanupResources=true
LogSlate: InvalidateAllWidgets triggered.  All widgets were invalidated
LogOnline: VeryVerbose: OSS: FOnlineSubsystemNull::Shutdown()
LogOnline: VeryVerbose: OSS: FOnlineAsyncTaskManager::Stop() ActiveTask:0000000000000000 Tasks[0/0]
LogOnline: VeryVerbose: OSS: FOnlineAsyncTaskManager::Exit() started
LogOnline: VeryVerbose: OSS: FOnlineAsyncTaskManager::Exit() finished
LogPlayLevel: Display: Shutting down PIE online subsystems
LogSlate: InvalidateAllWidgets triggered.  All widgets were invalidated
LogSlate: Updating window title bar state: overlay mode, drag disabled, window buttons hidden, title bar hidden
LogAudioMixer: FMixerPlatformXAudio2::StopAudioStream() called
LogAudioMixer: FMixerPlatformXAudio2::StopAudioStream() called
LogUObjectHash: Compacting FUObjectHashTables data took   1.71ms
LogPlayLevel: Display: Destroying online subsystem :Context_12
LogOnline: VeryVerbose: OSS: FOnlineSubsystemNull::Shutdown()`

**Comment by ssshammi** [comment]
It closes down even if i preview on device. So the example is not working for me

`LogTemp: Repeating last play command: VR Preview
LogPlayLevel: PlayLevel: No blueprints needed recompiling
LogHMD: Initializing OVRPlugin session
LogHMD: Allocating Oculus 3648 x 1840 rendertarget swapchain
PIE: New page: PIE session: Lobby (26-May-2022, 12:00:51 pm)
LogPlayLevel: Creating play world package: /Game/SharedSpaces/Maps/UEDPIE_0_Lobby
LogPlayLevel: PIE: StaticDuplicateObject took: (0.005249s)
LogAIModule: Creating AISystem for world Lobby
LogPlayLevel: PIE: World Init took: (0.001096s)
LogPlayLevel: PIE: Created PIE world by copying editor world from /Game/SharedSpaces/Maps/Lobby.Lobby to /Game/SharedSpaces/Maps/UEDPIE_0_Lobby.Lobby (0.006759s)
LogUObjectHash: Compacting FUObjectHashTables data took   0.86ms
LogOvrPlatform: Display: UOvrPlatformSubsystem::Initialize
LogOvrPlatform: Display: Login with current credentials
LogOvrPlatform: Display: UOvrPlatformSubsystem::InitWithWindowsPlatform: ovr_PlatformInitializeWindows successful
LogSharedSpaces: Display: Oculus platform successfully initialized.
LogSharedSpaces: Display: Use ASDW to move, mouse for camera orientation, C to change color and SPACE to jump.
LogAudio: Display: Creating Audio Device:                 Id: 5, Scope: Unique, Realtime: True
LogAudioMixer: Display: Audio Mixer Platform Settings:
LogAudioMixer: Display:     Sample Rate:                          48000
LogAudioMixer: Display:     Callback Buffer Frame Size Requested: 1024
LogAudioMixer: Display:     Callback Buffer Frame Size To Use:    1024
LogAudioMixer: Display:     Number of buffers to queue:           2
LogAudioMixer: Display:     Max Channels (voices):                32
LogAudioMixer: Display:     Number of Async Source Workers:       0
LogAudio: Display: AudioDevice MaxSources: 32
LogAudio: Display: Audio Spatialization Plugin: None (built-in).
LogAudio: Display: Audio Reverb Plugin: None (built-in).
LogAudio: Display: Audio Occlusion Plugin: None (built-in).
LogAudioMixer: Display: Initializing audio mixer.
LogAudioMixer: Display: 0: FrontLeft
LogAudioMixer: Display: 1: FrontRight
LogAudioMixer: Display: 0: FrontLeft
LogAudioMixer: Display: 1: FrontRight
LogAudioMixer: Display: 0: FrontLeft
LogAudioMixer: Display: 1: FrontRight
LogAudioMixer: Display: Using Audio Device Headphones (Oculus Virtual Audio Device)
LogAudioMixer: Display: Initializing Sound Submixes...
LogAudioMixer: Display: Creating Master Submix 'MasterSubmixDefault'
LogAudioMixer: Display: Creating Master Submix 'MasterReverbSubmixDefault'
LogAudioMixer: Display: Creating Master Submix 'MasterEQSubmixDefault'
LogAudioMixer: FMixerPlatformXAudio2::StartAudioStream() called
LogAudioMixer: Display: Output buffers initialized: Frames=1024, Channels=2, Samples=2048
LogAudioMixer: Display: Starting AudioMixerPlatformInterface::RunInternal()
LogAudioMixer: Display: FMixerPlatformXAudio2::SubmitBuffer() called for the first time
LogInit: FAudioDevice initialized.
LogAudio: Display: Audio Device (ID: 5) registered with world 'Lobby'.
LogSlate: Updating window title bar state: overlay mode, drag disabled, window buttons hidden, title bar hidden
LogLoad: Game class is 'SharedSpacesGameMode_C'
LogWorld: Bringing World /Game/SharedSpaces/Maps/UEDPIE_0_Lobby.Lobby up for play (max tick rate 0) at 2022.05.26-11.00.53
LogWorld: Bringing up level for play took: 0.002096
LogOnline: OSS: Creating online subsystem instance for: :Context_4
LogOnline: Verbose: OSS: Created thread (ID:2156).
LogSharedSpaces: Display: First player start without a tag.
LogOnlineVoice: OSS: Voice interface disabled by config [OnlineSubsystem].bHasVoiceEnabled
LogTemp: Warning: Using HMD
LogSharedSpaces: Display: Local character current destination:  
PIE: Server logged in
PIE: Play in editor total start time 2.892 seconds.
LogEngine: Changing dynamic resolution state.
LogHMD: Allocating Oculus 3648 x 1840 depth rendertarget swapchain
LogProfilingDebugging: Allocated a 1024 x 1024 texture for HMD canvas layer
LogSharedSpaces: Display: Must call get_signature first (1971051)
LogSharedSpaces: Display: FATAL ERROR: Login failure.
LogSharedSpaces: Display: Missing entitlement for 5227464203981184 (1971031)
LogSlate: Updating window title bar state: overlay mode, drag disabled, window buttons hidden, title bar hidden
LogWorld: BeginTearingDown for /Game/SharedSpaces/Maps/UEDPIE_0_Lobby
LogSlate: Window 'SharedSpaces Preview [NetMode: Standalone]  (64-bit/Windows) OculusHMD' being destroyed
LogSharedSpaces: Display: Shutdown
LogOvrPlatform: Display: UOvrPlatformSubsystem::Deinitialize
LogWorld: UWorld::CleanupWorld for Lobby, bSessionEnded=true, bCleanupResources=true
LogSlate: InvalidateAllWidgets triggered.  All widgets were invalidated
LogOnline: VeryVerbose: OSS: FOnlineSubsystemNull::Shutdown()
LogOnline: VeryVerbose: OSS: FOnlineAsyncTaskManager::Stop() ActiveTask:0000000000000000 Tasks[0/0]
LogOnline: VeryVerbose: OSS: FOnlineAsyncTaskManager::Exit() started
LogOnline: VeryVerbose: OSS: FOnlineAsyncTaskManager::Exit() finished
LogPlayLevel: Display: Shutting down PIE online subsystems
LogSlate: InvalidateAllWidgets triggered.  All widgets were invalidated
LogAudioMixer: FMixerPlatformXAudio2::StopAudioStream() called
LogAudioMixer: FMixerPlatformXAudio2::StopAudioStream() called
LogUObjectHash: Compacting FUObjectHashTables data took   0.82ms
LogPlayLevel: Display: Destroying online subsystem :Context_4
LogOnline: VeryVerbose: OSS: FOnlineSubsystemNull::Shutdown()
LogHMD: Warning: Destroying layer 2
LogHMD: Warning: Destroying layer 1
LogEngine: Changing dynamic resolution state.`

**Comment by els-oculus** [comment]
Hello ssshammi,

SharedSpaces checks for your entitlement, and that will fail if you do not specify app ids.  Currently we just exit the app when that happens.   If you want to continue running when failing entitlement check, you can modify the SharedSpacesGameInstance blueprint in your copy.   That could be useful during development.

The MobileAppId is for running on Quest.  The RiftAppId is for running on Windows (and other OSes), typically in the editor during development.  There are limitations to what works on Windows, however: launching roster and invite panels only work on Quest for example.

To have two different app ids, one for Quest and one for Windows, you need to create two apps on the Oculus dashboard.   One will be for Rift, and the other for Quest(store).  When you go to "Platform Services", you can group the two apps to share the same configuration (i.e. you won't have to write the destination configs twice).

**Comment by ssshammi** [comment]
So does it mean i can't test in preview mode on quest? How will it launch the invite panel. My new log is .  what do i need to check if the photon is working. 
	const FString serverAddress = TEXT("ns.exitgames.com");	// Connect to Photon cloud master server
	const FString AppID = TEXT("55f1427a-300e-3d6c-a3f2-94ee533800a5");	// Set your Photon AppID here
	const FString appVersion = TEXT("1.0");
 I dont know what server adress i need to add to Connect to Photon cloud master server if i am running it from the photon cloud server.  So i do not have the IP address.

`LogTemp: Repeating last play command: VR Preview
LogPlayLevel: PlayLevel: No blueprints needed recompiling
LogHMD: Initializing OVRPlugin session
LogHMD: Allocating Oculus 3648 x 1840 rendertarget swapchain
PIE: New page: PIE session: Lobby (31-May-2022, 11:21:30 am)
LogPlayLevel: Creating play world package: /Game/SharedSpaces/Maps/UEDPIE_0_Lobby
LogPlayLevel: PIE: StaticDuplicateObject took: (0.009512s)
LogAIModule: Creating AISystem for world Lobby
LogPlayLevel: PIE: World Init took: (0.001866s)
LogPlayLevel: PIE: Created PIE world by copying editor world from /Game/SharedSpaces/Maps/Lobby.Lobby to /Game/SharedSpaces/Maps/UEDPIE_0_Lobby.Lobby (0.011670s)
LogUObjectHash: Compacting FUObjectHashTables data took   2.16ms
LogOvrPlatform: Display: UOvrPlatformSubsystem::Initialize
LogOvrPlatform: Display: Login with current credentials
LogOvrPlatform: Display: UOvrPlatformSubsystem::InitWithWindowsPlatform: ovr_PlatformInitializeWindows successful
LogSharedSpaces: Display: Oculus platform successfully initialized.
LogSharedSpaces: Display: Use ASDW to move, mouse for camera orientation, C to change color and SPACE to jump.
LogAudio: Display: Creating Audio Device:                 Id: 5, Scope: Unique, Realtime: True
LogAudioMixer: Display: Audio Mixer Platform Settings:
LogAudioMixer: Display:     Sample Rate:                          48000
LogAudioMixer: Display:     Callback Buffer Frame Size Requested: 1024
LogAudioMixer: Display:     Callback Buffer Frame Size To Use:    1024
LogAudioMixer: Display:     Number of buffers to queue:           2
LogAudioMixer: Display:     Max Channels (voices):                32
LogAudioMixer: Display:     Number of Async Source Workers:       0
LogAudio: Display: AudioDevice MaxSources: 32
LogAudio: Display: Audio Spatialization Plugin: None (built-in).
LogAudio: Display: Audio Reverb Plugin: None (built-in).
LogAudio: Display: Audio Occlusion Plugin: None (built-in).
LogAudioMixer: Display: Initializing audio mixer.
LogAudioMixer: Display: 0: FrontLeft
LogAudioMixer: Display: 1: FrontRight
LogAudioMixer: Display: 0: FrontLeft
LogAudioMixer: Display: 1: FrontRight
LogAudioMixer: Display: 0: FrontLeft
LogAudioMixer: Display: 1: FrontRight
LogAudioMixer: Display: Using Audio Device Headphones (Oculus Virtual Audio Device)
LogAudioMixer: Display: Initializing Sound Submixes...
LogAudioMixer: Display: Creating Master Submix 'MasterSubmixDefault'
LogAudioMixer: Display: Creating Master Submix 'MasterReverbSubmixDefault'
LogAudioMixer: Display: Creating Master Submix 'MasterEQSubmixDefault'
LogAudioMixer: FMixerPlatformXAudio2::StartAudioStream() called
LogAudioMixer: Display: Output buffers initialized: Frames=1024, Channels=2, Samples=2048
LogAudioMixer: Display: Starting AudioMixerPlatformInterface::RunInternal()
LogAudioMixer: Display: FMixerPlatformXAudio2::SubmitBuffer() called for the first time
LogInit: FAudioDevice initialized.
LogAudio: Display: Audio Device (ID: 5) registered with world 'Lobby'.
LogSlate: Updating window title bar state: overlay mode, drag disabled, window buttons hidden, title bar hidden
LogLoad: Game class is 'SharedSpacesGameMode_C'
LogWorld: Bringing World /Game/SharedSpaces/Maps/UEDPIE_0_Lobby.Lobby up for play (max tick rate 0) at 2022.05.31-10.21.33
LogWorld: Bringing up level for play took: 0.002474
LogOnline: OSS: Creating online subsystem instance for: :Context_12
LogOnline: Verbose: OSS: Created thread (ID:5252).
LogSharedSpaces: Display: First player start without a tag.
LogOnlineVoice: OSS: Voice interface disabled by config [OnlineSubsystem].bHasVoiceEnabled
LogTemp: Warning: Using HMD
LogSharedSpaces: Display: Local character current destination:  
PIE: Server logged in
PIE: Play in editor total start time 2.946 seconds.
LogEngine: Changing dynamic resolution state.
LogHMD: Allocating Oculus 3648 x 1840 depth rendertarget swapchain
LogProfilingDebugging: Allocated a 1024 x 1024 texture for HMD canvas layer
LogSharedSpaces: Display: Must call get_signature first (1971051)
LogSharedSpaces: Display: FATAL ERROR: Login failure.
LogSharedSpaces: Display: Missing entitlement for 5227464283981184 (1971031)
LogSharedSpaces: Display: Failed to launch roster panel
LogSharedSpaces: Display: Testing
LogSharedSpaces: Display: Must call get_signature first (1971051)
LogSharedSpaces: Display: Testing
LogSharedSpaces: Display: Must call get_signature first (1971051)
LogSharedSpaces: Display: Testing
LogSharedSpaces: Display: Must call get_signature first (1971051)
LogSharedSpaces: Display: Friends List
LogSharedSpaces: Display: Failed to get list of friends
LogSharedSpaces: Display: Failed to fetch logged in user: Must call get_signature first (1971051)
LogSharedSpaces: Display: Failed to launch invite panel
LogSharedSpaces: Display: Failed to launch roster panel
LogSharedSpaces: Display: Testing
LogSharedSpaces: Display: Must call get_signature first (1971051)
LogSharedSpaces: Display: Failed to launch roster panel
LogSharedSpaces: Display: Testing
LogSharedSpaces: Display: Must call get_signature first (1971051)
LogSlate: Updating window title bar state: overlay mode, drag disabled, window buttons hidden, title bar hidden
LogWorld: BeginTearingDown for /Game/SharedSpaces/Maps/UEDPIE_0_Lobby
LogSlate: Window 'SharedSpaces Preview [NetMode: Standalone]  (64-bit/Windows) OculusHMD' being destroyed
LogSharedSpaces: Display: Shutdown
LogOvrPlatform: Display: UOvrPlatformSubsystem::Deinitialize
LogWorld: UWorld::CleanupWorld for Lobby, bSessionEnded=true, bCleanupResources=true
LogSlate: InvalidateAllWidgets triggered.  All widgets were invalidated
LogOnline: VeryVerbose: OSS: FOnlineSubsystemNull::Shutdown()
LogOnline: VeryVerbose: OSS: FOnlineAsyncTaskManager::Stop() ActiveTask:0000000000000000 Tasks[0/0]
LogOnline: VeryVerbose: OSS: FOnlineAsyncTaskManager::Exit() started
LogOnline: VeryVerbose: OSS: FOnlineAsyncTaskManager::Exit() finished
LogPlayLevel: Display: Shutting down PIE online subsystems
LogSlate: InvalidateAllWidgets triggered.  All widgets were invalidated
LogAudioMixer: FMixerPlatformXAudio2::StopAudioStream() called
LogAudioMixer: FMixerPlatformXAudio2::StopAudioStream() called
LogUObjectHash: Compacting FUObjectHashTables data took   2.23ms
LogPlayLevel: Display: Destroying online subsystem :Context_12
LogOnline: VeryVerbose: OSS: FOnlineSubsystemNull::Shutdown()`

**Comment by els-oculus** [comment]
I do not use the "Mobile Preview ES3.1 (PIE)" mode myself, but my understanding is that it is similar to the normal play-in-editor except that it uses the mobile rendering pipeline.  This means that It will use the Rift app id in that mode, and it will have the same limitations in terms of invite panels compared to running on device.

Now there are a few issues visible in your log:
- You are running in editor using a a Quest(AppLab) id, so that will definitely fail on Windows.   Use a Rift id.  Your app quits even before attempting to connect to Photon.   Make sure you use the correct ids in the right config variables.
- You can use Quest(AppLab) for your app (instead of Quest(Store)) but this will not let you share Platform Services settings between your Rift and Quest app.  That's OK, you can still repeat the same settings on both side.
- DATA USE CHECKUP: you must configure that, otherwise you will receive incomplete responses from the platform and things will fail at different places.
