### ISSUE TITLE
Problems to build in MacBook Pro max m1

### ISSUE THREAD

**Issue by yvasquezja** [oculus-samples/Unreal-SharedSpaces#17]
hello, I am trying to run this project but when compiling it tells me that photon and oculusPlatform is not compatible with this platform. Does this project only work on windows?

**Comment by els-oculus** [comment]
Yes, Oculus development is only well supported on Windows and Android (the latter being the OS used on Quest headsets).
The build files, such as UnrealEngine/Engine/Source/ThirdParty/Oculus/LibOVRPlatform/LibOVRPlatform.build.cs, make that explicit.

This said, I know that some devs emulate Windows on macOS, including macbook pros with M1 chips.

**Comment by yvasquezja** [comment]
Ok. Thanks
