### ISSUE TITLE
LUT Sample

### ISSUE THREAD

**Issue by owlandfox** [oculus-samples/Unreal-SharedSpaces#19]
I am trying to use the LUT rendering technique from the Oculus Samples in my Shared Spaces project but unsure how to add the necessary patch from the sample folder to the UE4 source code?

https://developer.oculus.com/documentation/unreal/unreal-samples/?locale=en_GB

"The color grading map requires that you apply the patch in the ColorGradingLUTPatch subdirectory." - I see the patch in the subdirectory but unsure how to install this to the Oculus Unreal source. Im assuming its by entering some command into CMD but theres no instruction on this.

**Comment by pr0-zac** [comment]
The Color Grade Map you reference is no longer the recommended way to apply LUTs. Good news is, the Oculus fork of 4.27 that SharedSpaces depends on already includes the new way with vulkan tonemap subpass. I recommend taking a look at the Graphics Showcase project to see how it works. 

You'll need to enable the config var with r.Mobile.TonemapSubpass=1 and setup a post process volume. Find all the details in the [Graphics Showcase blog post](https://developer.oculus.com/blog/graphics-showcase-using-vulkan-subpasses-in-ue4-for-performant-tone-mapping-on-quest/).

**Comment by pr0-zac** [comment]
Android Vulkan preview for the tonemap subpass is not currently supported. I'll be working on this in the next few weeks. Will let you know when a fix is available.

**Comment by owlandfox** [comment]
Excellent please do as its getting pretty annouying trying to edit in SM5 and only seeing how Vulkan looks once built to device. Thanks!

**Comment by owlandfox** [comment]
After the tonemapping working just fine this last week I attempted to switch the render preview over to Android from SM5 and it crashed the editor. Now I am unable to open the project to change render level back to SM5 as it crashes on open. When attempting to rebuild project from source it throws up some error lines in VS too. 

Output Log -
Fatal error: [File:D:/Oculus_Unreal/UnrealEngine/Engine/Source/Runtime/RenderCore/Private/RenderingThread.cpp] [Line: 902] 
Rendering thread exception:
Fatal error!

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000010

0x00007fff04fe2c15 UE4Editor-Renderer.dll!FMobileSceneRenderer::MobileTonemapSubpass() [D:\Oculus_Unreal\UnrealEngine\Engine\Source\Runtime\Renderer\Private\MobileShadingRenderer.cpp:1856]
0x00000035e0c0a028 UnknownFunction []
0x00000035e0c0a598 UnknownFunction []
0x00000035e0c0a010 UnknownFunction []
0x00007fff92eb21a0 UE4Editor-RHI.dll!GRHICommandList() []
0x0000016000000000 UnknownFunction []


Visual Studio - 
![image](https://user-images.githubusercontent.com/15714783/174305478-8f164b7b-8041-40f9-94f0-3f35bf2c38f0.png)

**Comment by owlandfox** [comment]
Update to above, I managed to get project open again by making tonemap subpass back to 0 in config. Just to further test this out I packaged out a build to applab and its crashing there too. Is Vulkan+Tonemap not supported on device too?

**Comment by owlandfox** [comment]
Just bumping this one as its holding us up on any further development. Thanks

**Comment by pr0-zac** [comment]
Apologies for the slow response. I was away for a few days. 

To summarize, you have the following issues:

1. No Android Vulkan preview in editor. 

I'm actively working on this. Will let you know when it is working. 

2. Exception in editor with tonemap subpass enabled
 
The error above indicates the generated LUT from the combine LUT pass is not available. Make sure the LUT is still set in the project and that the file is still there. The texture is used by the combine LUT pass to generate the ColorGradingTexture.

3. Tonemap subpass not working on device with your project but ok in Graphics Showcase

This is likely related to number 2. If the generated LUT is not available, it cannot be applied.  Is it crashing or just not applying the LUT?

**Comment by owlandfox** [comment]
"Make sure the LUT is still set in the project and that the file is still there." - Are you referring to the actual LUT texture PNG because that is definitely properly set in the post process on each map - 

![image](https://user-images.githubusercontent.com/15714783/175553383-6a422246-ecae-425c-9f52-5d9c053ad8c0.png)

If you are referring to a different file what is it?

So I ran a few process of elimination tests to try and target what was causing the crash with still no luck. Eventually I ended up resorting to removing all post process volumes from my maps but leaving tonemap turned on in config and still no luck so im really at a loss to know what else to try!

**Comment by owlandfox** [comment]
In my desperation to get this working I started from a fresh SharedSpaces repo and still getting a crash on device (and in editor 
 Vulkan preview but thats expected) at startup. Have you got tonemapping to work on your side with SharedSpaces? Can you think of anything specific related to the project that would cause it not to work?

Now that we have implemented tonemapping (albeit only previewing in SM5) and seen its effects it is now fundamental to our aesthetic (a music performance multiplayer space) so we really need to figure how to get this working.

**Comment by pr0-zac** [comment]
I was able to reproduce your issue today. It seems to be related to the skylight in the scene triggering a reflection capture which does a full render. This skylight render is crashing in the tonemap subpass logic. 

I was able to work around it by deleting the skylight from the scene. It worked with both color tint and tonemap LUT on device. I'll need to dig into it more to see exactly why this code path is crashing.

**Comment by owlandfox** [comment]
Oh thats great news, thanks so much for digging into this. Please keep me updated on the Vulkan preview progress.

**Comment by pr0-zac** [comment]
I found the cause of the skylight reflection capture render crash. Post processing flag is disabled when the capture renders, but it was still trying to run the tonemap subpass. Fix this by adding an extra check in MobileShadingRenderer.cpp > RenderForward() > Line 1069.

This: 
const bool bUseColorGradingLUT = (bUseMobileTonemapSubpass && (View.Family->EngineShowFlags.ColorGrading != 0) && (View.Family->EngineShowFlags.PostProcessing != 0));

Instead of this:
const bool bUseColorGradingLUT = (bUseMobileTonemapSubpass && (View.Family->EngineShowFlags.ColorGrading != 0));

I'll submit the fix to our fork of the engine.

**Comment by owlandfox** [comment]
This all works perfectly now thanks. If only we could apply some bloom (not possible anytime in the near future we know)
