### ISSUE TITLE
FB/Oculus Profile Avatar above character

### ISSUE THREAD

**Issue by owlandfox** [oculus-samples/Unreal-SharedSpaces#25]
Is it possible to have users fb/oculus profile avatar appear in the same space as the current username above players head? This would add a bit more personality for each users presence. I know we can pull it in to the roster and query ui so it must be feasible somehow

**Comment by yvasquezmonoku** [comment]
![image](https://user-images.githubusercontent.com/38009822/177611012-dcd33b75-284c-42ad-91af-1e9374450224.png)

**Comment by yvasquezmonoku** [comment]
what this does is download player information, in this case download the url of the user's profile image and assign it as a texture

**Comment by owlandfox** [comment]
Would this code go in the Shared Spaces character blueprint? There would need to be some rep notify event that serves the url/image texture to all clients connected to main game instance also I think

**Comment by owlandfox** [comment]
OK thanks so much for the help on this. The screenshot above is cut off on the right hand side - where are the On success, On Fail and Texture nodes connecting to?

**Comment by owlandfox** [comment]
When adding the get user widget it doesnt give me all the nodes needed to plug in? 

![image](https://user-images.githubusercontent.com/15714783/177816480-25f64daa-9932-4ecb-859a-9f5cbb31a688.png)

**Comment by yvasquezmonoku** [comment]
![image](https://user-images.githubusercontent.com/38009822/177819153-a693456c-8f89-41dc-8f25-5cd12791c03e.png)

**Comment by owlandfox** [comment]
Im sorry, I have basic knowledge with blueprints - what is the middle connector (target-IMG) called to add it from menu? Thanks for your patience!

**Comment by owlandfox** [comment]
Or is it a variable that needs adding and connecting?

**Comment by yvasquezmonoku** [comment]
it's not a variable, just on your image pin type "get IMG"
![image](https://user-images.githubusercontent.com/38009822/177823855-28237f0e-b6d6-4ea9-b811-4a0990ea3a61.png)

**Comment by owlandfox** [comment]
Just to confirm, what did you drag in to create the user photo in the graph? I am dragging in my plane mesh but not getting any option to select Get IMG in the menu 

![image](https://user-images.githubusercontent.com/15714783/177861302-283db708-5174-4073-bff6-14023420210c.png)

In your screenshot 'User Photo' looks like a variable in the menu. Is this something I need to set in the hierachy before dragging it in to the graph?

**Comment by yvasquezmonoku** [comment]
Wait, "Avatar" is a blueprint? if so, what I am showing you will not work because in my case it is an "image" of a widget. In your case you should do the following.
The material must be a right click parameter texture,Give it a name that you remember because that name is the one you should use in the material.
![image](https://user-images.githubusercontent.com/38009822/177863309-715629e9-5d9d-43e0-be64-6a8e613b5e53.png)
![image](https://user-images.githubusercontent.com/38009822/177863079-307839af-4d83-408e-93cd-4bc419cba85a.png)
luego tomas el plano en tu caso "Avatar" y creas un material dinamico, y de el sacas texture parameter  
![image](https://user-images.githubusercontent.com/38009822/177863026-92ef47b0-4bd1-464c-85f3-5aed06ebd445.png)

**Comment by yvasquezmonoku** [comment]
sorry, I had not noticed that IMG was my image and not parameter

**Comment by owlandfox** [comment]
OK this works! Awesome! Thanks so much for your patience and quick response!

**Comment by yvasquezmonoku** [comment]
a pleasure to help you

**Comment by deedox** [comment]
Hi, I am trying to do the same thing. I want to apply the quest user images and their names to multiple players, but I haven't figured out how to do it properly. It only applies to the first player. I would be very grateful if someone could help. Thanks
