### ISSUE TITLE
How to know when a user connects to my room?

### ISSUE THREAD

**Issue by yvasquezmonoku** [oculus-samples/Unreal-SharedSpaces#26]
Hello, As the title indicates, I want to know if there is any event that tells me that a player connected to my room?

**Comment by els-oculus** [comment]
The normal UE OnPostLogin/OnLogout events in your game mode may be what you are looking for.

![login_logout](https://user-images.githubusercontent.com/61444568/179262243-bace7280-5d25-4297-8390-c3168e692149.png)

**Comment by yvasquezmonoku** [comment]
I will try and comment. Thanks
