### ISSUE TITLE
Can I change the behavior when leaving the guardian area?

### ISSUE THREAD

**Issue by yvasquezmonoku** [oculus-samples/Unreal-SharedSpaces#31]
Hello, we have a question regarding the behavior of the plugin, currently when a client leaves the guard area, it disconnects and reconnects when returning to the area. We would like the client not to be disconnected, since sometimes when a client has several areas such as the sofa and when moving to that area they are disconnected. Is this possible? .

**Comment by pr0-zac** [comment]
I suspect the application may be getting backgrounded which triggers a call to Leave(). 

Check your logs for "Photon Client - Detected Application Quit".

If you see it, try commenting out the call to Leave() on line 39 of Plugins/PhotonNetDriver/Source/PhotonNetDriver/Private/PhotonLBClient.cpp.

**Comment by yvasquezmonoku** [comment]
I tried commenting on the line you indicated, but it keeps happening, every time I leave the guardian's area it goes out.

**Comment by els-oculus** [comment]
Leaving the guardian area forces your app to go to background.   That's an OS event that cannot be blocked.

```
08-09 22:58:25.462 21228 21431 D UE      : [2022.08.09-22.58.25:462][356]LogAndroid: Case APP_CMD_LOST_FOCUS
08-09 22:58:25.462 21228 21431 D UE      : LogAndroidEvents::EnqueueAppEvent : 10, [width=-1, height=-1], tid = 21431, APP_EVENT_STATE_WINDOW_LOST_FOCUS
08-09 22:58:25.475 21228 21430 D UE      : [2022.08.09-22.58.25:475][357]LogAndroidEvents: Display: LogAndroidEvents::DequeueAppEvent : 10, [width=-1, height=-1], APP_EVENT_STATE_WINDOW_LOST_FOCUS
08-09 22:58:25.475 21228 21430 D UE      : FAppEventManager::Tick processing, 10
08-09 22:58:25.546 21228 21228 D UE      : [GameActivity] onPause: stop memory reporter runnable
08-09 22:58:25.546 21228 21228 D UE      : [GameActivity] Unregistering sensor listeners
08-09 22:58:25.547 21228 21431 D UE      : Case APP_CMD_PAUSE
08-09 22:58:25.547 21228 21431 D UE      : [2022.08.09-22.58.25:547][362]LogAndroid: Case APP_CMD_PAUSE
08-09 22:58:25.547 21228 21431 D UE      : LogAndroidEvents::EnqueueAppEvent : 6, [width=-1, height=-1], tid = 21431, APP_EVENT_STATE_ON_PAUSE
08-09 22:58:25.547 21228 21431 D UE      : [2022.08.09-22.58.25:547][362]LogAndroid: event thread, suspending app, acquiring HW window lock.
08-09 22:58:25.547 21228 21431 D UE      : LogAndroidEvents::EnqueueAppEvent : 15, [width=-1, height=-1], tid = 21431, APP_EVENT_RUN_CALLBACK
08-09 22:58:25.547 21228 21431 D UE      : [2022.08.09-22.58.25:547][362]LogAndroid: AndroidEGL::  SuspendApp_EventThread, waiting for event manager to process. tid: 21431
08-09 22:58:25.547 21228 21228 D UE      : [GameActivity] ==============> GameActive.onPause complete!
08-09 22:58:25.558 21228 21430 D UE      : [2022.08.09-22.58.25:558][363]LogAndroidEvents: Display: LogAndroidEvents::DequeueAppEvent : 6, [width=-1, height=-1], APP_EVENT_STATE_ON_PAUSE
08-09 22:58:25.559 21228 21430 D UE      : FAppEventManager::Tick processing, 6
08-09 22:58:25.559 21228 21430 D UE      : [2022.08.09-22.58.25:559][363]LogVulkanRHI: FVulkanPipelineStateCacheManager: skipped saving because we only save if the PSOFC based one failed to load.
08-09 22:58:25.559 21228 21430 D UE      : [2022.08.09-22.58.25:559][363]LogAndroidEvents: Display: LogAndroidEvents::DequeueAppEvent : 15, [width=-1, height=-1], APP_EVENT_RUN_CALLBACK
08-09 22:58:25.559 21228 21430 D UE      : FAppEventManager::Tick processing, 15
08-09 22:58:25.559 21228 21430 D UE      : [2022.08.09-22.58.25:559][363]LogAndroidEvents: Display: Event thread callback running.
08-09 22:58:25.559 21228 21430 D UE      : [2022.08.09-22.58.25:559][363]LogAndroid: performing app backgrounding callback. 0x6ebab2e680
08-09 22:58:27.034 21228 21625 D UE      : [2022.08.09-22.58.27:034][363]LogTcpMessaging: Lost node '4382B00F411D4442B5046085556BBC45' on connection '127.0.0.1:46795'...
08-09 22:58:27.134 21228 21430 D UE      : [2022.08.09-22.58.27:134][363]LogCore: Display: AppLifetime: Application will deactivate
***** NOTE: Here is the callback to UPhotonLBClient::HandleApplicationEnterBackground()
08-09 22:58:27.135 21228 21430 D UE      : [2022.08.09-22.58.27:135][363]LogSharedSpaces: Display: Photon Client - Detected Application Quit
08-09 22:58:27.137 21228 21430 D UE      : [2022.08.09-22.58.27:137][363]LogNet: Photon Client - Detected Application Quit
08-09 22:58:27.137 21228 21430 D UE      : [2022.08.09-22.58.27:137][363]LogSharedSpaces: Display: Leave Room
08-09 22:58:27.139 21228 21430 D UE      : [2022.08.09-22.58.27:139][363]LogNet: Leave Room
08-09 22:58:27.140 21228 21430 D UE      : [GameActivity] Unregistering volume receiver
08-09 22:58:27.141 21228 21430 D UE      : [GameActivity] Unregistering battery receiver
08-09 22:58:27.141 21228 21430 D UE      : [GameActivity] Unregistering headset receiver
08-09 22:58:27.141 21228 21430 D UE      : [2022.08.09-22.58.27:141][363]LogCore: Display: AppLifetime: Application will enter background
08-09 22:58:27.141 21228 21430 D UE      : [2022.08.09-22.58.27:141][363]LogTemp: Android pause audio
08-09 22:58:27.142 21228 21430 D UE      : [2022.08.09-22.58.27:142][363]LogAudioMixerAndroid: Display: Suspending android audio renderer
08-09 22:58:27.142 21228 21431 D UE      : [2022.08.09-22.58.27:142][363]LogAndroid: Blocking renderer on invalid window.
08-09 22:58:27.142 21228 21431 D UE      : [2022.08.09-22.58.27:142][363]LogAndroid: Waiting for renderer to encounter blocking command.
08-09 22:58:27.142 21228 21583 D UE      : [2022.08.09-22.58.27:142][363]LogAndroid: Blocking renderer
08-09 22:58:27.142 21228 21583 D UE      : [2022.08.09-22.58.27:142][363]LogAndroid: RendererBlock release window callback
08-09 22:58:27.143 21228 21583 D UE      : [2022.08.09-22.58.27:143][363]LogVulkanRHI: Destroy swapchain ...
```

If the player going to background is the host, it's definitely better to immediately disconnect so that somebody else can assume the role of server.  

If it is a client, I think that the best option is to make the reconnection as seamless as possible.  Definitely some polish work would be required there, but that's the best route.

**Comment by yvasquezmonoku** [comment]
I understand. and there is no way to make photon not disconnect clients if not until a certain time?

**Comment by els-oculus** [comment]
No, because the app won't get scheduled by the OS at all after you have been notified that it goes to background.
Any timer would not have a chance to be triggered.

**Comment by yvasquezmonoku** [comment]
ooh, I understand. Well, I think the solution will be to display a message indicating reconnecting to the client. One last question, to show that message I can invoke it using "Bind Event to on leave room" , since when the client returns they see the level paused, which gives them the feeling that something is wrong, after seeing it paused for a few seconds it restarts, which is when it rejoins the room. I would like the client to see the reconnecting message when he comes back, so that he doesn't think that the game is stuck.

**Comment by els-oculus** [comment]
In the case of SharedSpaces, I see about a 1s delay for reconnection.
You definitely can display a message, or maybe just some icon that indicates reconnection, when the application reenters foreground.   Probably here:

![foreground](https://user-images.githubusercontent.com/61444568/184041863-459c59dd-b5a8-4d68-b08a-5195c93983a0.png)

**Comment by els-oculus** [comment]
However, even more important, is to properly handle a seamless reconnection.    Right now I see the character respawning at some random PlayerStart, and we have a mechanism to respawn at the exact same spot.

**Comment by yvasquezmonoku** [comment]
Thank you very much for the prompt response. Tomorrow I will see what you told me to be able to put the message or icon of reconnecting. On the other hand, the character reappears, I have a function that when the character comes out keeps its position and when I return it leaves it where it is, this thanks to the username that is saved when leaving. I see the same as you say that you have a mechanism for reappearance in the same place, I would like to see it anyway. Where can I see this mechanism that you tell me about?

**Comment by els-oculus** [comment]
I found the bug.   In SharedSpacesGameInstance blueprint, delete the node that unsets "Is Rejoining Room".

![incorrect](https://user-images.githubusercontent.com/61444568/184045454-fc2fbcdb-37bd-40d9-8f35-f3c852a6b967.png)

It should be like this.

![correct](https://user-images.githubusercontent.com/61444568/184045475-c6d01dea-643c-4e4a-8a57-711fa82322af.png)


So what this does is that when you rejoin the room, it will use your current location and rotation when opening the UE level.

![rejoin](https://user-images.githubusercontent.com/61444568/184045859-48a520ae-f2ee-4ccb-bc71-e2196feb9b05.png)

Now check our overloaded "Find Player Start" function in SharedSpacesGameMode.   You will see that we can detect when the spawn parameter sent to the server contains a location+rotation string.   

![game_mode](https://user-images.githubusercontent.com/61444568/184046158-df668568-3923-41e7-a197-edd644fcadb3.png)

This allows the server to spawn you at the right place.   How cool is that!

**Comment by yvasquezmonoku** [comment]
Wow. It looks great! Tomorrow I will do all this and tell me how everything turned out. Thank you very much for the help

**Comment by yvasquezmonoku** [comment]
Thank you very much. Everything works great.
