### ISSUE TITLE
Problems with users who are not members of my organization

### ISSUE THREAD

**Issue by yvasquezmonoku** [oculus-samples/Unreal-SharedSpaces#34]
Hello, again I have problems :)
We have a problem, and that is that any member that we invite to try our app must be part of the organization so that she can play. if he is not part of the organization that person starts the game but he cannot invite or start a level, since he never connects with the oculus service. We are submitting our app for review to the app lab but they reject us for this, since the tester cannot proceed to test because he is not a member of the organization. Is there any way they can try without being a member of the organization?

**Comment by yvasquezmonoku** [comment]
I will leave the log that I see when starting with a user who is not part of the organization
The first image is at startup. the second shows that I can not invite anyone and the third is when I select a level (destination)
I know this is because the oculus platform failed to initialize.

![image](https://user-images.githubusercontent.com/38009822/184408302-162de543-1afd-4b6c-ab2c-34970fad7d43.png)

![image](https://user-images.githubusercontent.com/38009822/184408336-c8b25c8f-fb7d-457c-8862-2817c7ee61b3.png)

![com monoku hush-20220812-120038](https://user-images.githubusercontent.com/38009822/184408388-9d18db07-2046-477d-8db7-eb3f9b4848d3.jpg)

**Comment by els-oculus** [comment]
Please send us the details of the rejection at devtech-showcases@meta.com

**Comment by yvasquezmonoku** [comment]
Thank you very much for answering. I already sent the mail

**Comment by volston7** [comment]
Hey there @els-oculus 

Quick Question: Can we build the VR Multiplayer Hosted on AWS Gamelift

**Comment by yvasquezmonoku** [comment]
Hello, do you mean doing a build and hosting the apk on the AWS?, or making
multiplayer with a dedicated server using the AWS?

**Comment by volston7** [comment]
@yvasquezmonoku  I mean Multiplayer with a dedicated server using AWS for VR (Quest 2). Are you familiar with this side of things and how you go about it

**Comment by yvasquezmonoku** [comment]
Hello, I think you should open a new topic with this, since it is something different from the topic of this thread.
At the moment regarding the dedicated server, I have very little knowledge, I have only made a global server.
https://docs.unrealengine.com/4.27/en-US/InteractiveExperiences/Networking/HowTo/DedicatedServers/

> @yvasquezmonoku Me refiero a multijugador con un servidor dedicado usando AWS para VR (Quest 2). ¿Estás familiarizado con este lado de las cosas y cómo lo haces?

**Comment by els-oculus** [comment]
@volston7 I opened issue #36 for you.

**Comment by yvasquezmonoku** [comment]
This was solved by sending the app to the app lab for testing, when it was approved, the destinations were also approved, and now any user who does not belong to the work group can play without problems.
