### ISSUE TITLE
app launches -> loads to the lobby-> Then CRASH!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by avikdutta111191** [oculus-samples/Unreal-SharedSpaces#37]
--------- beginning of crash
F/DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
F/DEBUG   : Build fingerprint: 'oculus/hollywood/hollywood:10/QQ3A.200805.001/37314400808900000:user/release-keys'
F/DEBUG   : Revision: '0'
F/DEBUG   : ABI: 'arm64'
F/DEBUG   : Timestamp: 2022-08-23 16:21:31+0530
F/DEBUG   : pid: 15497, tid: 15672, name: FTcpMes-ansport  >>> com.oculus.sho.SharedSpaces <<<
F/DEBUG   : uid: 10081
F/DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
F/DEBUG   : Cause: null pointer dereference
F/DEBUG   :     x0  0000000000000000  x1  00000000000007e6  x2  0000000000000008  x3  0000000000000017
F/DEBUG   :     x4  000000000000000a  x5  0000000000000033  x6  000000000000001e  x7  0000000000000028
F/DEBUG   :     x8  0000007e6cf49000  x9  6f4968ba48d5de2f  x10 0000000000000005  x11 00000000ffffffec
F/DEBUG   :     x12 0000005b0374a500  x13 0000005af1930200  x14 00000000000000d4  x15 000000c92a69c000
F/DEBUG   :     x16 0000000000989680  x17 0000000000002710  x18 0000007e8100a000  x19 0000007e28a4fd78
F/DEBUG   :     x20 0000007eca42cc00  x21 0000007e375df900  x22 0000007e28b45720  x23 f9064303637b2bb2
F/DEBUG   :     x24 80e114a49608bf80  x25 08da84f56f977f80  x26 0000007eca42cc00  x27 0000000000000000
F/DEBUG   :     x28 0000007e271cc400  x29 0000007eca42cb00
F/DEBUG   :     sp  0000007eca42ca40  lr  0000007e676e9cb0  pc  0000007e676e9cb0
F/DEBUG   : 
F/DEBUG   : backtrace:
F/DEBUG   :       #00 pc 000000000a769cb0  /data/app/com.oculus.sho.SharedSpaces-bcZVJ77yNMgj5Tv1JzLsdA==/lib/arm64/libUE4.so (_ZN11FMessageBus7ForwardERK10TSharedRefI15IMessageContextL7ESPMode1EERK6TArrayI15FMessageAddress22TSizedDefaultAllocatorILi32EEERK9FTimespanRKS0_I14IMessageSenderLS2_1EE+636) (BuildId: 6000778fb72bda48628213016a8f2951c8a1a745)
F/DEBUG   :       #01 pc 000000000a7691e0  /data/app/com.oculus.sho.SharedSpaces-bcZVJ77yNMgj5Tv1JzLsdA==/lib/arm64/libUE4.so (_ZN14FMessageBridge23ReceiveTransportMessageERK10TSharedRefI15IMessageContextL7ESPMode1EERK5FGuid+1608) (BuildId: 6000778fb72bda48628213016a8f2951c8a1a745)
F/DEBUG   :       #02 pc 00000000091b6060  /data/app/com.oculus.sho.SharedSpaces-bcZVJ77yNMgj5Tv1JzLsdA==/lib/arm64/libUE4.so (FTcpMessageTransport::Run()+1580) (BuildId: 6000778fb72bda48628213016a8f2951c8a1a745)
F/DEBUG   :       #03 pc 0000000009810f1c  /data/app/com.oculus.sho.SharedSpaces-bcZVJ77yNMgj5Tv1JzLsdA==/lib/arm64/libUE4.so (FRunnableThreadPThread::Run()+164) (BuildId: 6000778fb72bda48628213016a8f2951c8a1a745)
F/DEBUG   :       #04 pc 00000000096ee328  /data/app/com.oculus.sho.SharedSpaces-bcZVJ77yNMgj5Tv1JzLsdA==/lib/arm64/libUE4.so (FRunnableThreadPThread::_ThreadProc(void*)+84) (BuildId: 6000778fb72bda48628213016a8f2951c8a1a745)
F/DEBUG   :       #05 pc 00000000000d5c44  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36) (BuildId: 74793b832f73c27f2be0922f70cc8e16)

**Comment by els-oculus** [comment]
I would check a few things first:
1) Make sure you are using the Oculus branch of UE4.
2) Make sure your have both your **Oculus** and **Photon** application properly configured:
https://github.com/oculus-samples/Unreal-SharedSpaces/blob/main/Documentation/SharedSpaces.md#d-oculus-application-configuration

**Comment by avikdutta111191** [comment]
The app runs fine on the the device  associated with the original developer account. 
The problem rises when I installed it on a  device associated with a different developer account.

**Comment by els-oculus** [comment]
While in development (i.e. not distributed through the Quest Store or App Lab), only members of the dev team are entitled to run the app.   You can add team members to your org on the Oculus dashboard.  You can also create test users that can run your app.

If not entitled, your app should not crash, however.   I tested this and my version simply exits without crash.
