### ISSUE TITLE
fatal error C1083: Cannot open include file: 'OVR_ChallengeCreationType.h' when building with added plugins

### ISSUE THREAD

**Issue by Motanum** [oculus-samples/Unreal-SharedSpaces#38]
hi, i tried adding the 3 plugins form this sample project to my game. My game uses unreal 4.27.2.

But when I compile the code to launch the editor, I get the error 
`D:\UnrealProjects\Musical-Range\Plugins\OVRPlatform\Source\OVRPlatform\Public\OVRPlatformEnums.h(30): fatal error C1083: Cannot open include file: 'OVR_ChallengeCreationType.h': No such file or directory`

I tried checking my Game.Build.CS but still not luck. Any idea how to fix this issue?

Build.cs is 
`using UnrealBuildTool;

public class MusicalRange : ModuleRules
{
	public MusicalRange(ReadOnlyTargetRules Target) : base(Target)
	{
        PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;

        PublicDependencyModuleNames.AddRange(new string[] { "Core", 
            "CoreUObject",
            "Engine",
            "InputCore",
            "PakFile",
            "ImageWrapper",
			"HeadMountedDisplay",
			"Niagara",
			"UMG",
			"MidiAsset",
            //"UnrealEd"

			//Subsystems
			"OnlineSubsystem",
            "OnlineSubsystemNull",
            "OnlineSubsystemUtils",

			//DLCs
			"DLCName"
		});

		PrivateDependencyModuleNames.AddRange(
            new string[] {
                "Json",
                "JsonUtilities",
                "LibOVRPlatform",
                "OculusUtils",
            });

        if (Target.Platform == UnrealTargetPlatform.Win64)
        {
            PublicDependencyModuleNames.AddRange(new string[]
            {
				//"OnlineSubsystem",
				//"OnlineSubsystemUtils",
				//"Steamworks",
				"OnlineSubsystemSteam"
            });
        }

        if (Target.Platform == UnrealTargetPlatform.Android)
		{

			PublicDependencyModuleNames.AddRange(new string[]
			{
					"LibOVRPlatform"
			});

        }

        PrivateDependencyModuleNames.AddRange(new string[] {  });
		
		PublicIncludePaths.AddRange(new string[] {"Plugins/Online/OnlineSubsystemSteam/Public", "Plugins/Online/OnlineSubsystemSteam/Classes" });

        MinFilesUsingPrecompiledHeaderOverride = 1;
        bUseUnity = true;

    }
}
`

**Comment by yvasquezmonoku** [comment]
Hello! Are you using the git version of the engine?  https://github.com/Oculus-VR/UnrealEngine/tree/4.27 
It also tries to install the Oculus application for Windows, it installs some libraries and add-ons that avoid some errors when compiling some Oculus modules.

**Comment by els-oculus** [comment]
yvasquezmonoku is correct, you need the Oculus branch of UE4.27.
You can find the instructions in the [README](https://github.com/oculus-samples/Unreal-SharedSpaces/blob/main/README.md).

**Comment by Motanum** [comment]
Hi! I am now using the Oculus build of the Engine and compilation and function calling doesn't generate any errors.
