### ISSUE TITLE
Invitation is never sent 

### ISSUE THREAD

**Issue by bidonjour** [oculus-samples/Unreal-SharedSpaces#4]
When using the Invite Panel, the invite is actually never sent to the other headset.
Steps to reproduce :
- Go on the Invite Panel
-  Invite one friend owning the sharedspaces app
- Validate
- A message is prompted : The invite has been sent
- But actually the other friend never receive anything in the notification as specified in the documentation ...

I've added some log in the C++ UOculusPlatformSubsystem::GroupPresenceLaunchInvitePanel() method, and I notice that the callback that should be called when closing the invite panel is never called. See the comment below

```
void UOculusPlatformSubsystem::GroupPresenceLaunchInvitePanel(
	const TArray<FOculusId>& SuggestedUsers,
	const FOculusPlatformOnGroupPresenceInvitePanelComplete& Callback)
{
	UE_LOG(LogOculusPlatform, Verbose, TEXT("UOculusPlatformSubsystem::GroupPresenceLaunchInvitePanel"));

	ovrInviteOptionsHandle InviteOptions = ovr_InviteOptions_Create();

	for (int32 UserIndex = 0, TotalUsers = SuggestedUsers.Num(); UserIndex < TotalUsers; ++UserIndex)
	{
		ovr_InviteOptions_AddSuggestedUser(InviteOptions, SuggestedUsers[UserIndex]);
	}

	LogEntry(TEXT("Launching invite panel."));

	AddRequestDelegate(ovr_GroupPresence_LaunchInvitePanel(InviteOptions), FOculusPlatformMessageOnComplete::CreateLambda(
		[this, Callback](ovrMessageHandle Message, bool bIsError)
		{
			// CODE HERE IS NEVER EXECUTED
			bool bInvitesHaveBeenSent = false;

			if (bIsError)
			{
				ovrErrorHandle Error = ovr_Message_GetError(Message);
				FString ErrorMessage(ovr_Error_GetMessage(Error));
				LogError(FString::Printf(TEXT("Error launching group presence invite panel: %s"), *ErrorMessage));
			}
			else
			{
				ovrInvitePanelResultInfoHandle InvitePanelResultInfoHandle = ovr_Message_GetInvitePanelResultInfo(Message);
				bInvitesHaveBeenSent = ovr_InvitePanelResultInfo_GetInvitesSent(InvitePanelResultInfoHandle);

				LogEntry(FString::Printf(TEXT("Group presence invite panel launch complete.  %s sent."), bInvitesHaveBeenSent?TEXT("Invites"):TEXT("No invites")));
			}

			Callback.ExecuteIfBound(!bIsError, bInvitesHaveBeenSent);
		}));

	ovr_InviteOptions_Destroy(InviteOptions);
}
```

The only thing working for me now is when 2 users go in the public purple room. Any other type of connection requiring to use Oculus UI like the invite panel doesn't work unfortunately.

I was wondering if someone succeed to invite a friend ? I can't see what I'm doing wrong. Everything is setup correctly in my project and in the Oculus Dashboard.

**Comment by els-oculus** [comment]
Hello @bidonjour,

We want to  help you investigate this issue and we will need some additional details.
Please reach out to us at devtech-showcases@fb.com and mention this project and issue.

**Comment by IronWrath** [comment]
Hi, I am also having the same issue, but my Settings > Notifications > Social > Friends Activity is turned ON.
