### ISSUE TITLE
Pawn UI

### ISSUE THREAD

**Issue by owlandfox** [oculus-samples/Unreal-SharedSpaces#40]
We have made some adjustments to the locomotion of our project to first person from the original third person view as we found with ASW enabled we were getting a lot of jitter and artefacts on player motion. Works much better now but in doing so the roster and invite panels are harder to navigate and land on in first person view. To combat this we have created a Pawn UI model that appears only in clients view - this contains some general settings such as volume/sfx etc but we would like to include the roster/invite screen into here. How best to access it / pull in into UMG as when previously discussed it seems this is being pulled from outside of UE and from Oculus directly. Thanks

**Comment by pr0-zac** [comment]
The roster and invite panels are system UI. The simplest approach would be to add buttons for each to your custom UI, and call the same blueprint nodes seen in the trigger blueprints:
"Group Presence Launch Invite Panel"
"Group Presence Launch Roster Panel"

If you want to integrate it more into you own UI, take a look at the quick invite documentation:
https://developer.oculus.com/documentation/unreal/ps-quick-invite/
