### ISSUE TITLE
Oculus Menu not being removed after Invite/Roster panel closed

### ISSUE THREAD

**Issue by owlandfox** [oculus-samples/Unreal-SharedSpaces#42]
I had to go into the Shared Spaces demo to ensure this wasnt just happening in my project - After clicking Done in invite or roster panels the roster/ivite panel disappears but Main Oculus Navigation bar remains on screen unless Menu button is tapped. 

This is not expected behaviour and definitely wasnt happening in previous Oculus OS version. Expected behaviour should be that Oculus OS nav bar disppears with the invite/roster panel when Done is tapped.

**Comment by els-oculus** [comment]
Yes, I have noticed that behavior in newer OS versions.
I'll ask on our internal boards.

**Comment by owlandfox** [comment]
Hi, was there any further knowledge around this? We would like to submit to applab very soon but this functionality is not a great user experience and feels a little broken. The fact that the oculus navbar remains after roster/invite panel is deactivated means that they must essentially be uncoupled. It would be great to not have to show the oculus navbar as it has no functionality here. Is there a way to just show roster/invite panel alone? Thanks

**Comment by els-oculus** [comment]
I agree that it breaks the flow.  You should still submit to AppLab as this is not something that you can fix on your end.
I'll close this issue as it is outside of SharedSpaces control, but I'll escalate internally.
