### ISSUE TITLE
How does voip work on sharespace

### ISSUE THREAD

**Issue by yvasquezmonoku** [oculus-samples/Unreal-SharedSpaces#46]
We are trying to enable voice chat within our game. we have the configuration of DefaultEngine.ini
```
[OnlineSubsystem]
DefaultPlatformService=Oculus
bHasVoiceEnabled=true
[voice]
bEnabled=true
```
I see that in shared spaces there is "connect request" and with ovr platform we have "void start", which has a "user id" input. We have put this id obtained by "platform get Logged inuser" of the users who enter the room, but it still doesn't work. We don't really know how it works and where we should put these voip functions. We would be very grateful if you could tell us how to make the voice chat work.

**Comment by yvasquezmonoku** [comment]
Reviewing I see that "voipAccept" and "voipStart" ask me for the player's id, which I think I have problems, because the id of the clients on the server shows them to me as if it were the same as the one on the server and those of the clients it shows all 0. I am saving this id as I do with img url, username. but I don't understand why they are not saved correctly. I hope you can help me see how to implement this in sharespaces.

![image](https://user-images.githubusercontent.com/38009822/199026323-d6810387-1a9a-4eb0-89fd-d363d39256a5.png)
![image](https://user-images.githubusercontent.com/38009822/199026152-7b259f39-4075-44db-9897-e56f46abc3b2.png)

**Comment by els-oculus** [comment]
VOIP is not implemented in the Unreal version of SharedSpaces.
The main reason is that at the time of writing that sample,  Photon's VOIP was only available for Unity.

They do have this library: https://www.photonengine.com/en-US/sdks#voice-sdkvoiceandroid
But there's no UE integration as far as I know.    It's doable, so if you end up making this work, we would gladly look at your pull request!

**Comment by yvasquezmonoku** [comment]
this for photon voip but no voice chat support on oculus?

**Comment by yvasquezmonoku** [comment]
Thank you very much for the help, I'll check, and I'm updating anything
