### ISSUE TITLE
Photon netdriver is not in use

### ISSUE THREAD

**Issue by juaxix** [oculus-samples/Unreal-SharedSpaces#49]
I don't think the project is really using the Photon netdriver, as you are missing that in the config file `DefaultEngine.ini` : 
```
[/Script/Engine.GameEngine]
+NetDriverDefinitions=(DefName="GameNetDriver",DriverClassName="/Script/PhotonNetDriver.PhotonIpNetDriver")

[/Script/Engine.Engine]
!NetDriverDefinitions=ClearArray
+NetDriverDefinitions=(DefName="GameNetDriver",DriverClassName="/Script/PhotonNetDriver.PhotonIpNetDriver",DriverClassNameFallback="/Script/OnlineSubsystemUtils.IpNetDriver")
+NetDriverDefinitions=(DefName="DemoNetDriver",DriverClassName="/Script/Engine.DemoNetDriver",DriverClassNameFallback="/Script/Engine.DemoNetDriver")

[/Script/OnlineSubsystemUtils.IpNetDriver]
NetConnectionClassName="/Script/PhotonNetDriver.PhotonNetConnection"

[/Script/PhotonNetDriver.PhotonIpNetDriver]
!ChannelDefinitions=ClearArray
+ChannelDefinitions=(ChannelName=Control, ClassName=/Script/Engine.ControlChannel, StaticChannelIndex=0, bTickOnCreate=true, bServerOpen=false, bClientOpen=true, bInitialServer=false, bInitialClient=true)
;+ChannelDefinitions=(ChannelName=Voice, ClassName=/Script/Engine.VoiceChannel, StaticChannelIndex=1, bTickOnCreate=true, bServerOpen=true, bClientOpen=true, bInitialServer=true, bInitialClient=true)
+ChannelDefinitions=(ChannelName=Actor, ClassName=/Script/Engine.ActorChannel, StaticChannelIndex=-1, bTickOnCreate=false, bServerOpen=true, bClientOpen=false, bInitialServer=false, bInitialClient=false)
NetConnectionClassName="/Script/PhotonNetDriver.PhotonNetConnection"
ConnectionTimeout=80.0
InitialConnectTimeout=120.0
NetServerMaxTickRate=30
MaxNetTickRate=120
KeepAliveTime=0.2
MaxClientRate=15000
MaxInternetClientRate=10000
RelevantTimeout=5.0
SpawnPrioritySeconds=1.0
ServerTravelPause=4.0
TimeoutMultiplierForUnoptimizedBuilds=1
RecentlyDisconnectedTrackingTime=120

```

once you do that it will crash in the ipnetdriver, because you need to fix how you get the game instance and from that the subsystem for the client, then, once you fix that crash you need to handle the handshake properly or it won't accept the connection ,there will be no correct login and the PIE session is not joined...
After that, you need fix how to properly set all the photon connection, join room op, etc. 
Are you still working on this project?
Cheers

**Comment by pr0-zac** [comment]
The PhotonNetDriver is specified in DefaultEngine.ini [here](https://github.com/oculus-samples/Unreal-SharedSpaces/blob/main/Config/DefaultEngine.ini#L33).

**Comment by juaxix** [comment]
Thanks for your response. 

If you make a diff against that config you mention and the params I posted before, you will notice the missing settings that the engine needs to actually use the net driver, otherwise you can debug it and see that it is instancing the default connection and ipnetdriver instead of the one you implemented, (setting the appid is the easy part in this config info, and you are getting data in the dashboard because you are connecting but you are not getting any data from the actual replication of the game, it would be much more data in the graphs). 
UNetDriver::TickFlush is where the server handles gathering and replicating actor info (via UNetDriver::ServerReplicateActors), and it's also where the NetDriver's ConnectionlessHandler is ticked and has its outgoing packets flushed (you can debug this and UNetDriver::FlushHandler, UNetDriver::LowLevelSend) to see that there is no data being sent with this photon net driver. 
The stateless connect handler component, is what handles the initial handshake between a server and a potential client, so debugging this may help if there seems to be some issue with this handshake (in StatelessConnectHandlerComponent.h/.cpp there is more info). 
You could also try to set the verbosity of the LogHandshake log category to provide more info on what is happening, more info on debugging networking issues here: https://udn.unrealengine.com/s/article/Debugging-and-Profiling-Multiplayer-Games

**Comment by pr0-zac** [comment]
Sounds like you are seeing replication data sent to the IPNetDriver instead of the PhotonIPNetDriver. This might be triggered by a bad ConnectURL sent to UPhotonIpNetDriver::InitConnect(). You can see that if OculusAddr.IsValid fails it sets bIsPassthrough and uses the IPNetDriver. Perhaps something isn't configured correctly.

**Comment by pr0-zac** [comment]
Since we haven't heard back, assuming that the problem is resolved. Feel free to re-open if needed.

**Comment by juaxix** [comment]
It's valid, because you can see in the logs my oculus username
`LogSharedSpaces: Display: Logged in username: juaxix`

so it's hitting this node
![image](https://user-images.githubusercontent.com/996806/208890453-df0007d2-5928-4e1a-910a-c5736fcd603b.png)

. 

and I can't see the other player either (noy using standalone nor listen-server modes)
![image](https://user-images.githubusercontent.com/996806/208890392-525151fb-551f-4812-8522-e58eed629afe.png)

The UPhotonIpNetDriver is never created nor used...see the dashboard for the appid:
![image](https://user-images.githubusercontent.com/996806/208890687-5ec00095-71cf-4ed0-9399-38cebe73d721.png)

the only thing that you are doing is creating the room and joining it, but the data layer is not used for replication... 36bytes is nothing compared with all the data that a replication uses...
are you sure you want to use Photon as netdriver or only for specific data?

**Comment by pr0-zac** [comment]
Thanks for the explanation and screenshots. It looks like you are testing in editor. I think this is the source of the problem. The PhotonNetDriver works as expected on device. We will need to spend some time looking at why this isn't working on PC as it would be helpful for testing. 

Also note that the lobby is a private room, so you would need to invite the other player to see them in there. You can use the purple room, which is public, for quick tests. Invites will only work on device.

[This project was also released on AppLab](https://www.oculus.com/experiences/quest/4540942155998634/). I recall having 6 players in the same room when testing it.

**Comment by juaxix** [comment]
Thanks but, I only have one device...
