### ISSUE TITLE
C2065 Errors for OculusPlatformSubsystem.cpp

### ISSUE THREAD

**Issue by LAYTAT** [oculus-samples/Unreal-SharedSpaces#5]
Hi, I am having trouble compiling this game using a windows machine. I am using the generated .sln file with Visual Studio. 
I see a lot of undeclared identifiers for **OVR_XXX** APIs. May I ask how do I solve it?

**Comment by els-oculus** [comment]
Are you using the Oculus fork of the Unreal Engine?
https://github.com/Oculus-VR/UnrealEngine

**Comment by lmcquade** [comment]
@LAYTAT please follow these instructions to make sure your UnrealEngine and GitHub accounts are associated correctly:
https://www.unrealengine.com/en-US/ue4-on-github

**Comment by LAYTAT** [comment]
Followed those steps and redid them, it worked.
