### ISSUE TITLE
UE5 support

### ISSUE THREAD

**Issue by JTheDev2703** [oculus-samples/Unreal-SharedSpaces#50]
Hello!
Are there any plans to get shared spaces available to UE5 soon? I'm using v46 from Oculus branch but I'm getting a lot of errors in the OVRPlatforms plugin due to missing methods. 

thank you in advance

**Comment by pr0-zac** [comment]
We're aware of the OVRPlatform issues and we are working on an update to the UE5 fork that will correct this. Unfortunately the project will not run with UE5 until we release that update. We will update this issue once the update is released.

**Comment by KavanBahrami** [comment]
What are the OVRPlatform issues that won't be resolved until the project is updated to UE5?

**Comment by pr0-zac** [comment]
New main-5.x branch is available now with UE5 support. Depends on v49.
