### ISSUE TITLE
Packaging apk fails for Shipping Configuration 

### ISSUE THREAD

**Issue by antitheos** [oculus-samples/Unreal-SharedSpaces#55]
Trying to publish our own version of Shared Spaces from main-5.x on UE5.1
When we try to publish with shipping configuration we receive the following error

```
UATHelper: Packaging (Android (ASTC)): ERROR: Non-editor build cannot depend on non-redistributable modules. D:\dev\samples\Unreal-SharedSpaces\Binaries\Android\SharedSpaces-Android-Shipping-arm64.so depends on 'ToolMenus', 'ToolWidgets'.
UATHelper: Packaging (Android (ASTC)): Dependant modules 'ToolWidgets', 'OculusUtils'
PackagingResults: Error: Non-editor build cannot depend on non-redistributable modules. D:\dev\samples\Unreal-SharedSpaces\Binaries\Android\SharedSpaces-Android-Shipping-arm64.so depends on 'ToolMenus', 'ToolWidgets'.
UATHelper: Packaging (Android (ASTC)): Non-editor build cannot depend on non-redistributable modules.
```

Looks like issue **OculusUtils** is using **ToolWidgets**
found following [OculusUtils.Build.cs](https://github.com/oculus-samples/Unreal-SharedSpaces/blob/main-5.x/Plugins/OculusUtils/Source/OculusUtils/OculusUtils.Build.cs)
```
PrivateDependencyModuleNames.AddRange(
			new string[]
			{
				"CoreUObject",
				"Engine",
				"Slate",
				"SlateCore",
				"OculusXRHMD",
				"DeveloperSettings",
				"OVRPluginXR",
				"ToolWidgets"
			}
		);

```

any thoughts on how we can publish? or does the 5.x branch not support publishing

**Comment by antitheos** [comment]
Just checked **ToolWidgets** is not a dependency in the 4.27 branch
(https://github.com/oculus-samples/Unreal-SharedSpaces/blob/main-4.27/Plugins/OculusUtils/Source/OculusUtils/OculusUtils.Build.cs)

any feedback on how it is used in 5.x branch?

**Comment by antitheos** [comment]
seems the ToolWidget package is being used for developer telemetry. i commented out that code and the removed the package dependency and was able go package. not sure this correct long term solution, but it allows my team to continue working on project.

**Comment by KavanBahrami** [comment]
I just noticed that my issue is just a repeat of yours from a day or so earlier. Thanks for posting the temp solution.

**Comment by pr0-zac** [comment]
Thanks for raising the issue. There was an error with the dialog box logic updated for UE5.1. I pushed a [fix](https://github.com/oculus-samples/Unreal-SharedSpaces/commit/b70845d61020a653537d1511f260892045d65b2c).
