### ISSUE TITLE
For Distribution / Shipping Build Config -  non-redistributable modules package error

### ISSUE THREAD

**Issue by KavanBahrami** [oculus-samples/Unreal-SharedSpaces#57]
SharedSpaces "main-5.x" branch
using UE "oculus-5.1" branch

I changed my ProjectSettings>Packaging> For Distribution to TRUE / Shipping Build Config and got this error. When I turn it back to false / Development Build Config I'm able to package as expected.

Is this something on my end or something with the packaged utils? Not sure if this is just SS or the oculus UE build, haven't tested it independently. I'm still actively trying to sort this issue and will update with more info as I gather it.

```
UATHelper: Packaging (Android (ASTC)): ERROR: Non-editor build cannot depend on non-redistributable modules. H:\GitHub\Oculus\SharedSpaces_5x\Unreal-SharedSpaces\Binaries\Android\SharedSpaces-Android-Shipping-arm64.so depends on 'ToolMenus', 'ToolWidgets'.
UATHelper: Packaging (Android (ASTC)): Dependant modules 'ToolWidgets', 'OculusUtils'
UATHelper: Packaging (Android (ASTC)): Non-editor build cannot depend on non-redistributable modules.
UATHelper: Packaging (Android (ASTC)): Took 12.4677296s to run dotnet.exe, ExitCode=6
UATHelper: Packaging (Android (ASTC)): UnrealBuildTool failed. See log for more details. (H:\GitHub\UnrealEngine\Oculus\UE5\UnrealEngine\Engine\Programs\AutomationTool\Saved\Logs\UBT-SharedSpaces-Android-Shipping_2.txt)
UATHelper: Packaging (Android (ASTC)): AutomationTool executed for 0h 6m 9s
UATHelper: Packaging (Android (ASTC)): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (Android (ASTC)): BUILD FAILED
PackagingResults: Error: Non-editor build cannot depend on non-redistributable modules. H:\GitHub\Oculus\SharedSpaces_5x\Unreal-SharedSpaces\Binaries\Android\SharedSpaces-Android-Shipping-arm64.so depends on 'ToolMenus', 'ToolWidgets'.
```

**Comment by KavanBahrami** [comment]
I tested UE "oculus-5.1" branch solo, packaging the AndroidPermissions sample in distribution.TRUE shipping build config, and it worked without the error. So it seems to just be the SharedSpaces sample.

I'm going to work on some other things before doing another fresh download / rebuild to test my setup further. ~~Hopefully someone will be able to confirm or deny this being a real bug in the meantime, if not,~~ I'll be back with that update.
** I see that issue #55 is also regarding this same issue, they commented out some code to temporarily keep moving.

**Comment by pr0-zac** [comment]
Thanks for raising the issue. There was an error with the dialog box logic updated for UE5.1. I pushed a [fix](https://github.com/oculus-samples/Unreal-SharedSpaces/commit/b70845d61020a653537d1511f260892045d65b2c). 

Going to close this issue. Lets consolidate further conversation to #55.
