### ISSUE TITLE
4.27 Pachakge Windows Fail

### ISSUE THREAD

**Issue by staniekmarcin** [oculus-samples/Unreal-SharedSpaces#58]
When i try to package my project i get this errors. Android all configs are fine and Windows Editor Is fine.
![image](https://user-images.githubusercontent.com/45049175/221821223-0f4fc36f-b3a8-4a56-a3fd-108e3c743e7d.png)

**Comment by carbonadmin** [comment]
any idea what should i change to make it work?

**Comment by carbonadmin** [comment]
it happens only trying to Package game for Windows

**Comment by yvasquezmonoku** [comment]
Hi, you have installed all the dependencies in your windows. I recommend you install the oculus app on your pc, this helps to install everything you need on your pc

**Comment by staniekmarcin** [comment]
I have Oculus app on my PC. This message weirdly shows that in OVRPlatform plugin and OculusOnline Subsystem Soemthing is duplicated.

**Comment by yvasquezmonoku** [comment]
Does this error appear in the test project or are you doing it in a new one?

**Comment by staniekmarcin** [comment]
In a new one.

**Comment by staniekmarcin** [comment]
Our Project. Tried recompile rebuild full etc.

**Comment by yvasquezmonoku** [comment]
Check if the same thing happens in the test project

**Comment by staniekmarcin** [comment]
Test config of out project or OculusShardesSpaces?

**Comment by yvasquezmonoku** [comment]
Yes, try building Oculus SharedSpaces to see if you get the same error.

**Comment by AlexThiv** [comment]
@staniekmarcin It seems like your project uses the `Online Subsystem Oculus` plugin, which is not used in SharedSpaces.
You can disable it in the Plugins menu
![image](https://user-images.githubusercontent.com/46505821/224165120-ae82b32e-c882-4ef5-a564-25e9ea064af5.png)

In SharedSpaces we integrated our own OVRPlatform plugin which replace the functionalities from the Online Subsystem Oculus.
