### ISSUE TITLE
changes to MakeOvrApplicationOptions node, minor issues (?) 

### ISSUE THREAD

**Issue by KavanBahrami** [oculus-samples/Unreal-SharedSpaces#61]
The most recent updates, I think, changed the Make OvrApplicationOptions node.

When the project loads it has three errors because that node is set to receive three pins that no longer exist:
Destination Api Name, Lobby Session Id, Match Session Id

This takes place in the commented section titled "Exit application to another application"
I just refresh the node and it cleans itself up and can then compile, but if this is the case, the team might want to clean that bit up and push it again.

**Comment by AlexThiv** [comment]
Hi @KavanBahrami,
Opening up a fresh version using [Unreal 5.1](https://github.com/Oculus-VR/UnrealEngine/tree/oculus-5.1) didn't show the errors you mentioned. It is correct that the MakeOvrApplicationOptions did change from the previous OVRPlatform implementation. Was UE open when you pull?

Here is what the node should look like
![image](https://user-images.githubusercontent.com/46505821/224180738-fc3ddd33-c1a9-4622-8267-f6b716ea6e7f.png)

You can also see the full function here https://github.com/oculus-samples/Unreal-SharedSpaces/blob/main-5.x/Documentation/SharedSpaces.md#6-external-application-portal

If I understand your message it seems like it might have reverted to the previous node implementation. Let me know if that helps and if you still have issues.

**Comment by KavanBahrami** [comment]
@AlexThiv Thanks for the clarification. I did a rebuild of the project in VS and the node was updated.
I'll close this issue. Best,
