### ISSUE TITLE
Unable to launch Invite

### ISSUE THREAD

**Issue by dav01d** [oculus-samples/Unreal-SharedSpaces#62]
Did a clean pull of SharedSpaces, and of the Unreal engine Oculus build: oculus-5.1.1-release-1.82.0-v50.4
Updated Photon AppId
Removed the entitlement check from GameInstance
Built to headset from Unreal
Walked over to invite, and I get this error:

![iVIYdtMvgp](https://user-images.githubusercontent.com/14636906/228948695-464648d3-e980-4665-b15d-168f1f296c6b.jpg)

Here's a close up of the log:
![image](https://user-images.githubusercontent.com/14636906/228948956-e52e8645-9c3c-438b-80fd-6ed0c2ee84b5.png)

Hmmm 🤔 Any ideas?

**Comment by AlexThiv** [comment]
Hi @dav01d,

Have you setup the application as described [here](https://github.com/oculus-samples/Unreal-SharedSpaces/blob/main-5.x/Documentation/SharedSpaces.md#d-oculus-application-configuration).

To be able to use invitations and destinations the application must be configured. As you noted that you disabled the entitlement check, I suppose that you didn't get the application set up and set the application id, to ensure a quick testing. The invites, roster and group presence are features that requires the application to be setup.

Let us know if you still encounter issues after setting up the application.

**Comment by dav01d** [comment]
Ahh how naive of me, I completely forgot DUC steps. I've used SS before to great success in UE4's flavor but this is a new AppID. Completely missed it.

One awkward thing (out of scope of this question but I'd appreciate any thoughts):
The Menu Quest menu button is on the left hand, and I used that to trigger a menu that includes Invite Friends, etc.
But once that menu loads, Dash takes over and you can't exit Dash with your left hand, only your right. It is a little cumbersome, and of course the right button is already reserved (so no menu spawning on the right) and the App has lost focus (so no easy way to read the Menu button on the left to Exit).

Just trying to think of a way to make the button clicking flow easier for users.

Thanks!
