### ISSUE TITLE
Avatar user Image for clients

### ISSUE THREAD

**Issue by deedox** [oculus-samples/Unreal-SharedSpaces#63]
Hi, sorry for the late reply. I was very buss the last month. I hope that you still can help me.
I manage to make the names working but I'm  struggling with the user images. This how far I came but with no luck. I'm not able to download the user image for the client characters..
Basically what I want is get each users image and apply them to my custom character mesh.
![usrimg_1](https://user-images.githubusercontent.com/9035271/230528550-28f41cf2-6a8a-4dec-a981-8ea5667fdce1.jpg)
![usrimg_2](https://user-images.githubusercontent.com/9035271/230528552-38e36e3b-fc22-484d-9a92-77be773c7cb0.jpg)

_Originally posted by @deedox in https://github.com/oculus-samples/Unreal-SharedSpaces/issues/60#issuecomment-1499865498_

**Comment by jasonmeisel** [comment]
Looking at your code, I think the issue might be that you're trying to send the Texture as an RPC parameter. Instead, just make the URL a replicated variable (like you did with the Username). Then each client can load the image themselves.

Let me know if that helps!

**Comment by deedox** [comment]
Thank you! This is what I have but now the client gets the servers profile image and the server has nothing applied..
![Screenshot 2023-04-12 045901](https://user-images.githubusercontent.com/9035271/231336896-65439e73-2164-4220-aac4-bd013224c0bc.jpg)

**Comment by jasonmeisel** [comment]
Does the API return the correct URL locally for each client? If so, you just need to replicate those URLs, then load the image from the URL when it replicates. Here's some more information on replication: https://docs.unrealengine.com/4.27/en-US/InteractiveExperiences/Networking/Actors/Properties/

Essentially, you can make it work exactly as the Username works already.

**Comment by deedox** [comment]
Thank you! I managed to make it work.
