### ISSUE TITLE
'State' is deprecated: 

### ISSUE THREAD

**Issue by dav01d** [oculus-samples/Unreal-SharedSpaces#66]
At compile we get a load of warnings, all effectively saying:

_LogPlayLevel: Warning: UAT: PhotonNetDriver/Source/PhotonNetDriver/Private/PhotonIpNetDriver.cpp(259,20): warning: 'State' is deprecated: EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]_

I'm assuming this will be fixed before the next update?

**Comment by AlexThiv** [comment]
Thanks @dav01d for reporting this.
Yes we have an update coming soon that will contain the fix.
