### ISSUE TITLE
Packaging Failure - Errors and Warnings

### ISSUE THREAD

**Issue by Baileyj925** [oculus-samples/Unreal-SharedSpaces#67]
Followed all instructions for building UE5.1 from source/Creating Shared Spaces Sample. 

Here is a list of the errors and warnings generated from shipping build. Any help appreciated. 

LogObj: Error: LoadConfig (/Script/Engine.Default__RendererSettings): import failed for VelocityPass in: False
LogClass: Warning: Function UOculusUtilsLibrary::SortComponentsByName defines MetaData key "ComponentClass" which contains short type name "ActorComponent". Suggested pathname: "/Script/Engine.ActorComponent". Module:OculusUtils File:Public/OculusUtilsLibrary.h
LogAutomationTest: Warning: LogClass: Function UOculusUtilsLibrary::SortComponentsByName defines MetaData key "ComponentClass" which contains short type name "ActorComponent". Suggested pathname: "/Script/Engine.ActorComponent". Module:OculusUtils File:Public/OculusUtilsLibrary.h
LogOVRPlugin: Error: CreateFoveationProfile() failed: required extensions not enabled: XR_FB_foveation 0 (arvr\projects\integrations\OVRPlugin\Src\Util\CompositorOpenXR.cpp:8724)
PackagingResults: Warning: 'slCreateEngine' is deprecated: first deprecated in Android 30 [-Wdeprecated-declarations]
LogAudioMixer: Warning: Audio Thread Command from SetListenerTransforms()() took 1.148600 milleseconds to execute
LogAudioMixer: Warning: Audio Thread Command from SetListenerTransforms()() took 1.150200 milleseconds to execute
LogAudioMixer: Warning: Audio Thread Command from SetListenerTransforms()() took 1.365400 milleseconds to execute
LogAudioMixer: Warning: Audio Thread Command from SetListenerTransforms()() took 1.382600 milleseconds to execute
LogAudioMixer: Warning: Audio Thread Command from SetListenerTransforms()() took 1.397500 milleseconds to execute
LogAudioMixer: Warning: Audio Thread Command from SetListenerTransforms()() took 1.164600 milleseconds to execute
LogAudioMixer: Warning: Audio Thread Command from SetListenerTransforms()() took 1.190500 milleseconds to execute
PackagingResults: Warning: 'MixInBufferFast' is deprecated: Use equivalent function in FloatArrayMath.h Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
PackagingResults: Warning: 'MixInBufferFast' is deprecated: Use equivalent function in FloatArrayMath.h Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
PackagingResults: Warning: 'MixInBufferFast' is deprecated: Use equivalent function in FloatArrayMath.h Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
LogAudioMixer: Warning: Audio Thread Command from SetListenerTransforms()() took 1.194000 milleseconds to execute
PackagingResults: Warning: 'slCreateEngine' is deprecated: first deprecated in Android 30 [-Wdeprecated-declarations]
PackagingResults: Warning: 'GameSessionName' is deprecated: Use NAME_GameSession. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
PackagingResults: Warning: 'OculusTouch_Right_System_Click' is deprecated: This key has been deprecated and will be removed. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
PackagingResults: Warning: 'SkeletalMesh' is deprecated: Replaced by SkinnedAsset. Use GetSkinnedAsset()/SetSkinnedAsset() instead, or GetSkeletalMeshAsset/SetSkeletalMeshAsset() when called from a USkeletalMeshComponent. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
PackagingResults: Warning: 'slCreateEngine' is deprecated: first deprecated in Android 30 [-Wdeprecated-declarations]
PackagingResults: Warning: 'State' is deprecated: EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
PackagingResults: Warning: 'State' is deprecated: EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
PackagingResults: Warning: 'State' is deprecated: EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
PackagingResults: Warning: 'State' is deprecated: EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
PackagingResults: Warning: 'State' is deprecated: EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
PackagingResults: Warning: 'State' is deprecated: EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
PackagingResults: Warning: 'State' is deprecated: EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
PackagingResults: Warning: 'State' is deprecated: EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
PackagingResults: Warning: 'State' is deprecated: EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
PackagingResults: Warning: 'State' is deprecated: EConnectionState State will be made private. Use GetConnectionState and SetConnectionState to access State instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile. [-Wdeprecated-declarations]
PackagingResults: Error: undefined symbol: ovr_ApplicationOptions_SetDestinationApiName
PackagingResults: Error: undefined symbol: ovr_ApplicationOptions_SetLobbySessionId
PackagingResults: Error: undefined symbol: ovr_ApplicationOptions_SetMatchSessionId
PackagingResults: Error: undefined symbol: ovr_ApplicationOptions_SetRoomId
PackagingResults: Error: undefined symbol: ovr_AvatarEditorOptions_Create
PackagingResults: Error: undefined symbol: ovr_AvatarEditorOptions_SetSourceOverride
PackagingResults: Error: undefined symbol: ovr_ChallengeOptions_Create
PackagingResults: Error: undefined symbol: ovr_ChallengeOptions_SetDescription
PackagingResults: Error: undefined symbol: ovr_ChallengeOptions_SetEndDate
PackagingResults: Error: undefined symbol: ovr_ChallengeOptions_SetIncludeActiveChallenges
PackagingResults: Error: undefined symbol: ovr_ChallengeOptions_SetIncludeFutureChallenges
PackagingResults: Error: undefined symbol: ovr_ChallengeOptions_SetIncludePastChallenges
PackagingResults: Error: undefined symbol: ovr_ChallengeOptions_SetLeaderboardName
PackagingResults: Error: undefined symbol: ovr_ChallengeOptions_SetStartDate
PackagingResults: Error: undefined symbol: ovr_ChallengeOptions_SetTitle
PackagingResults: Error: undefined symbol: ovr_ChallengeOptions_SetViewerFilter
PackagingResults: Error: undefined symbol: ovr_ChallengeOptions_SetVisibility
PackagingResults: Error: undefined symbol: ovr_GroupPresenceOptions_Create
PackagingResults: Error: undefined symbol: ovr_GroupPresenceOptions_SetDeeplinkMessageOverride
PackagingResults: Error: undefined symbol: ovr_GroupPresenceOptions_SetDestinationApiName
PackagingResults: Error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
PackagingResults: Error: linker command failed with exit code 1 (use -v to see invocation)
PackagingResults: Error: Unknown Error

**Comment by Gipfel** [comment]
I know that error, I achieved it by combining the SharedSpaces with SharedAnchors Sample or by just adding the Photon Framework to my SharedAnchors Project. But a complete new downloaded SharedSpaces Projects had worked for me.

I still have no Solution for that … sorry
https://communityforums.atmeta.com/t5/General-Development/UE5-Shared-Spaces-Shared-Spatial-Anchors/td-p/1066105?emcs_t=S2h8ZW1haWx8YWNjZXB0X2FzX3NvbHV0aW9uX3JlbWluZGVyfExLQVRCMzlBUkNOQ1ZSfDEwNjc0NDB8T1RIRVJTfGhL
https://forums.unrealengine.com/t/meta-oculus-shared-scene-sample/1246966

**Comment by AlexThiv** [comment]
Updated to 5.2 and fixed some settings related to UE5.

Let us know if you run into other issues.
