### ISSUE TITLE
UE 5.3.2 bug

### ISSUE THREAD

**Issue by alefriant** [oculus-samples/Unreal-SharedSpaces#73]
Hi guys, the release for 5.3.2 has a LOT of delay for the client, the host works perfect and the app running in the editor seems to be ok, the problem appears when building for the quest standalone. I'm going back to the 5.2 because with this problem the 5.3.2 is not functional at all.

**Comment by AlexThiv** [comment]
Hi @alefriant, thanks for raising this issue. Can you elaborate on what kind of delay are you having, are you talking about network latency? Also when you say you are going back to 5.2, do you mean using latest of this project with UE5.2 or going back to an earlier version of this project as well?

**Comment by alefriant** [comment]
Hi @AlexThiv 
I tried it again and seems it was a problem with the servers that day, the code works perfect in a second attempt, so I'm gonna close this. 
FYI: I'm running my game with this code and both v60 SDK, MetaXR and MetaXRPlatforms, works perfect in both + 5.3.2 at least in my scenarios. Thanks a lot for sharing this template!
