### ISSUE TITLE
Infra diagram

### ISSUE THREAD

**Issue by developer1ab** [oculus-samples/Unreal-SharedSpaces#75]
Actually this is not a issue but a self learning infra pic summarized by me. hope this helpful to others who wanna go through this whole topic. I have to admit it do spend me 3 days to go through whole infra and successfully setup the demo project, This is the note I left for future coming guys to lower the learning time. 
![SharedSpaceInfra](https://github.com/oculus-samples/Unreal-SharedSpaces/assets/102498614/31b013d4-bc39-49cb-a0e9-30038f3360ea)

**Comment by AlexThiv** [comment]
Thanks for providing us this diagram. We will look into adding a version in our documentation.
