### ISSUE TITLE
MIT license for Unreal.

### ISSUE THREAD

**Issue by alefriant** [oculus-samples/Unreal-SharedSpaces#85]
Hey @AlexThiv I saw that you modified the Unity-SharedSpaces to an MIT license, could be possible to do that to the Unreal version please? 

Today in Unreal we have a very restricting License, and I expect to launch my game and to be cross platform, even if I still don't have the way to connect it with mobile and pc, I'm pretty sure that will happens in the near future considering the new posture of Meta of making this a more open ecosystem, and I'm pretty sure that friends in pc playing in 1st or 3rd person who can't use their hands against their headset friends which can use their hands will bring more people to the VR world. 
And as I see with an open license I won't need to rebuild everything for my pc and mobile version. 

TY!

![image](https://github.com/user-attachments/assets/1093dc9a-ef2b-4c04-8ffd-cb77a7b94bd6)

![image](https://github.com/user-attachments/assets/8d90f1b7-229e-4dfb-8041-11526fd867ce)

**Comment by jasonmeisel** [comment]
Hi @alefriant, you can find more information about the licensing here: https://github.com/oculus-samples/Unreal-SharedSpaces/tree/main-5.x?tab=readme-ov-file#license

The Source directory is already under MIT License. We can't put the entire repo under MIT, as it includes Meta and Photon SDKs that are under their own licenses.

What exactly is the Oculus SDK License preventing you from doing? Would it be helpful to put the Content directory under MIT as well?

**Comment by alefriant** [comment]
Hi @jasonmeisel I didn't know that the directory was under MIT, I misunderstood that. Thanks for the clarification, I don't need Meta or Photon to be MIT.
Thank you!
