### ISSUE TITLE
Photon Voice

### ISSUE THREAD

**Issue by alefriant** [oculus-samples/Unreal-SharedSpaces#86]
Hey @AlexThiv @jasonmeisel 

I've seen that Unity has the Photon Voice enabled. Could you please, please, please!! add that feature to the Unreal version? The Photon code has been something impossible to handle on my own.
Today when players jump inside the common destination they can't talk between them, which is critical to engage the users and make them to be friends in the Meta app later, so they will be able to continue talking using the Meta social platform later if they decide to add each other (People app days ago, Chat today). 

Thanks again for this great template.

Alejandro!

![image](https://github.com/user-attachments/assets/d0f901cc-2198-4e77-973f-8fb0dfe0f355)

**Comment by AlexThiv** [comment]
Hi @alefriant,

We don't currently have plans to add photon voice, or voice chat in this project at the moment. But we will put it on our list of potential future projects. Thanks for asking.
Additionaly to photon voice you could also look in integration Unreal's [EOS Voice Chat plugin](https://dev.epicgames.com/documentation/en-us/unreal-engine/eos-voice-chat-plugin)

**Comment by alefriant** [comment]
Hey @AlexThiv 
EOS Voice Chat plugin is the solution to my problem, thanks a lot for that tip!  💯 🥇 👍 
(I was blinded by Photon, aggg)
