### ISSUE TITLE
Replication of Vr pawn 

### ISSUE THREAD

**Issue by Jdongre** [oculus-samples/Unreal-SharedSpaces#87]
I want to add default  vr pawn as my game pawn instead of third person character  i was able to replicate host side pawn that is whatever action host is doing it is getting replicated but for client its not happening the client side replication are reflecting on the server I tried Repnotify for sending the movement data to the server but it's not smooth compared  to host replication is there another efficient way to replicate the  vr  pawn I am using epic's  unreal 5.3.2

**Comment by alefriant** [comment]
Hi @Jdongre 
The VR Template extension plugin it's an all inclusive for that purpose and they have a community to solve questions, https://vreue4.com/
Has everything you need for replication. 

Good luck!

**Comment by jasonmeisel** [comment]
There are many resources like the one @alefriant mentioned that can help you here. Since it's outside the scope of Shared Spaces, I'm closing this issue, but feel free to discuss on the [Meta Quest Developer Forums](https://communityforums.atmeta.com/t5/Developer/ct-p/developer).
