### ISSUE TITLE
EOS new branch issues

### ISSUE THREAD

**Issue by alefriant** [oculus-samples/Unreal-SharedSpaces#89]
Hey @jasonmeisel !

I began to try the new file clean as it comes from your Git before migrating anything. 
It compiles, and seems the EOS is working?, the problem I have is I can't travel from the Lobby to any room.
The invitation panel doesn't work either. 
**There is no transition screen** when loading the game or when traveling from a room to the Lobby. 
I wasn't able to try it with more users because I can't invite either. 

Unreal: 5.4.3 v68 (Oculus version 1.100.0-v100.0-v68.0)
VS2022 Pro 17.10
Android Studio Flamingo, etc. Everything as indicated in Unreal Documentation.

Notes:
- If I load the room from the Meta Developers portal and I start the game from any room, I was able to travel to the Lobby. 
- This takes "a lot", let's say 10-20 seconds to load the Lobby. And when back in the Lobby I can't go back to that room either. 
- I can see the visitor in the portal - in this case 1 visitor in the blue room joining it directly. (picture attached)

I'm attaching the logs I have, if you could help me with that will be great, Thank you!! 

<img width="949" alt="image" src="https://github.com/user-attachments/assets/7459de41-b4e8-4b11-a35a-ada10af31c44">
<img width="878" alt="image" src="https://github.com/user-attachments/assets/5cae9384-d842-407c-bd73-7ee21e9fb4c7">

- Here is the attempt Starting in the Blue Room using the Meta Go to Destination Button:

<img width="1154" alt="image" src="https://github.com/user-attachments/assets/8c9d08a5-a4fe-4630-8180-c495a286ff97">

- Invitation panel error:
<img width="561" alt="image" src="https://github.com/user-attachments/assets/59dfebf9-c2a4-4ee2-a262-06397049914e">

- Here a picture Starting directly in the Lobby loading the game from the Headset:

<img width="578" alt="image" src="https://github.com/user-attachments/assets/30b3e9a5-2620-4772-836d-c4e78dcc44a7">

**Comment by jasonmeisel** [comment]
Since you are seeing a "User does not have app in library" error, that most likely means the app is not receiving entitlement. Without entitlement, the app cannot access Destinations or info about them.

Have you followed all the steps for getting entitlement for the app? Did you upload an APK with this package name to a release channel for this app ID?

**Comment by alefriant** [comment]
What a noob, I was too focused in the new EOS that I forgot the basic settings.

PS: It works, has some issues but works, I'll submit a list in some free time later.

![BadDobby](https://github.com/user-attachments/assets/48cb4ec4-ead1-471e-aa9e-ee455ac1ab5e)
