### ISSUE TITLE
Please add project configuration links to the docs

### ISSUE THREAD

**Issue by kokashking** [oculus-samples/Unreal-SharedSpaces#92]
Hi,

Can you please add a couple of links to your documentation so it would be easier to understand how to configure the project?

here are the two pages:
https://developers.meta.com/horizon/documentation/unreal/ps-setup/
https://developers.meta.com/horizon/documentation/unreal/unreal-packaging-and-preparing-your-new-project

I think it makes sens to put it somewhere in the Part D (Oculus Application Configuration) in (https://github.com/oculus-samples/Unreal-SharedSpaces/blob/main-5.x/Documentation)

Best and thx for the code

**Comment by jasonmeisel** [comment]
Thanks for your feedback!
