### ISSUE TITLE
OnlineSubsystemOculus

### ISSUE THREAD

**Issue by elmachotroso** [oculus-samples/Unreal-SharedSpaces#93]
Hello. I'm trying to integrate MetaXRPlatform SDK on my 5.3.1 forked engine.

1. I've seen in this project that there's no OnlineSubsystemOculus. I understand this is deprecated when using Meta XR Platform? (I'm using v60)

2. Is it intentional that the DefaultEngine.ini is DefaultPlatformService=Null and in effect, when we run the app in Windows with Editor, any calls to the function will go to the fail cases?

3. Does it mean we can only test this on an apk installed on Meta Quest?

**Comment by jasonmeisel** [comment]
It is correct that OnlineSubsystemOculus is disabled in the project, and you should be using the Meta XR Platform directly instead.

The sample does work on Windows, but certain platform features like invites are not functional. Is there any particular failure case you're experiencing?

**Comment by elmachotroso** [comment]
Sorry for the late response. Well your project has been helpful in order for me to understand and break down the SDK and reassemble it with our current fork. Your mention of directly using API was also a great clue. I realized how outdated Meta's own documentation is.
