### ISSUE TITLE
SOS: In high-latency environments, users are dropping.

### ISSUE THREAD

**Issue by alefriant** [oculus-samples/Unreal-SharedSpaces#97]
Hey @jasonmeisel If you could help me with this will be great, I think should be modify a number and that's all. 

I'm testing my game based on SharedSpaces with headsets from different countries. Sometimes, when there’s a significant delay, the clients disconnect or the host leaves the session. Is there any way to increase the waiting time? In my case, I prefer lower quality for testing purposes over losing the connection between my team members.

I only found this number (originally 15), but I’m not sure if it will help, in the instructions in the bp says negative for infinite waiting time:

![image](https://github.com/user-attachments/assets/6648eb90-a55f-4ac3-9305-655bd40a9408)

**Comment by jasonmeisel** [comment]
To clarify, is your issue that players are disconnecting after already being connected to the session?

**Comment by alefriant** [comment]
@jasonmeisel 
Yes, when players are already connected, usually with more than 3 users and with some delay, the clients often end up trapped in the transition map. 
When playing nearby (in the same city), this doesn't happen.
Sometimes even the host lost is kicked out, or it's migrated to another client. 

- When only 2 players and good bandwidth, doesn't happen either, none of the problems mentioned above occurs. We tested this from different continents. Seems if the connection is stable nothing happens. 

To have in consideration we are always in the People App using it as a voice chat platform. 

It would be great to adjust something to make the clients wait a bit longer for the host before disconnecting or migrate host, for me even if this decrease the gameplay quality.

Thanks!

**Comment by jasonmeisel** [comment]
Thanks for the info. Could you also provide logs of what's happening on the clients?

**Comment by alefriant** [comment]
I'll get those asap. TY

**Comment by jasonmeisel** [comment]
Are you still hitting this issue? If so, please provide the logs and open a new task. Thanks!
